### ISSUE TITLE
Payroll charge

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#101]
Hi @theharrisonmoore - we've noticed an issue with the data, specifically around the payroll. It says in the spreadsheet to render the 'How much were you charged?' alongside the payroll they were paid by. However, if they select they were paid by a payroll, they say which payroll (picking from a list) but aren't asked how much they were charged. So we can't render this. 

With this in mind are you ok with us for now simply listing the name of the payroll on the agency profile and not how much they were charged for it?

**Comment by theharrisonmoore** [comment]
@thejoefriel I see, good spot!

We do need to include the payroll charge as it's a point of contention for many workers and something they want to see at a glance. I've fixed this now so that the question 'How much were you charged?' is part of the review. I've updated the question flow diagram (see screenshot below)

<img width="722" alt="Screenshot 2019-04-18 at 07 34 11" src="https://user-images.githubusercontent.com/45825100/56338981-a3176780-61ac-11e9-87df-3d461dc830c0.png">

**Comment by thejoefriel** [comment]
OK thanks @theharrisonmoore - we'll modify the database accordingly

**Comment by thejoefriel** [comment]
@theharrisonmoore Do you mind sending a link to this revised question flow so I can update our resources issue for reference?

**Comment by theharrisonmoore** [comment]
Of course. Here it is: https://whimsical.co/CY3c7ofLGBup9R5Fs73BqV
<https://signup.earwig.work/>

**Comment by thejoefriel** [comment]
Perfect! Thanks!

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore I realised there's still issues with the logic of this question flow. 

At the moment if they say they use a payroll we ask them the name and how much they were charged and this is then rendered under Pays using following Payrolls

However, if they select they don't use a Payroll, we don't then ask them for a name but we do ask them how much they are charged. Currently we can't render this as there isn't a name to put it alongside. It makes the logic very complicated in terms of showing the profiles correctly. 

Can you please explain in case I'm just not understanding it properly? The cleaner we can make this input the better for rendering. Thanks!

**Comment by thejoefriel** [comment]
Also @theharrisonmoore - would it be ok if we just removed the 'were you charged' and instead on the 'how much were you charged' provide an option for this to be zero? This will make it much cleaner to get all the data we want in one place and also reduces the number of questions the user has to answer

**Comment by theharrisonmoore** [comment]
Hi Joe,

Thanks for being so thorough with this. You're right; you've definitely
revealed some bad logic here. The reason it flows in this way is that
sometimes (extremely rarely, like 1% of the time) agencies forego using
payrolls and pay workers themselves. The agency would then charge the
worker a fee for processing payroll themselves. In this case, it would be
the agency charging workers and therefore the agency profile would need a
section showing how much they charge, which isn't currently in the designs.
It is too complicated and too much extra work to add this now.

For now, let's assume 100% of agencies use payrolls to pay workers and
therefore workers would always choose 'Yes' to the question of 'Were you
paid via a payroll/umbrella?' Let's go with what you said: the 'How much
were you charged?' question with the option for a zero. I've updated the
flow here: https://whimsical.co/CY3c7ofLGBup9R5Fs73BqV

<https://signup.earwig.work/>

**Comment by theharrisonmoore** [comment]
@thejoefriel Ignore the question numbers in the Agency question flow, now. They're jumbled up and I'm not sure how to tidy them. So long as the question numbers flow and make sense for workers on the front-end when they're giving reviews, that's all that matters.

**Comment by thejoefriel** [comment]
Thanks @theharrisonmoore and no worries at all on the logic - it's amazing how difficult it is to cover all the various angles once you start diving really deep into it! 

I think that all makes sense. I'm going to integrate this myself tomorrow so will follow the flow you've provided and will let you know if we come up against any further issues 👍
