### ISSUE TITLE
This icon needs to be white

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#1013]
This icon needs to be white

![IMG_0478](https://user-images.githubusercontent.com/45825100/72338032-81a3c780-36bb-11ea-823e-a32456690c3c.jpg)

**Comment by thejoefriel** [comment]
@theharrisonmoore just to confirm, this isn't one of the closed issues. This has been done and will be merged into production shortly. https://github.com/yalla-coop/earwig/issues/991

**Comment by theharrisonmoore** [comment]
Okay, thanks

Best,
Harrison Moore
Sparky & Founder
*earwig <http://earwigwork.com>*

ᐧ
