### ISSUE TITLE
Added user stories

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#102]
Hi @theharrisonmoore - there's been a number of user stories added after contract. You've helpfully marked these in the spreadsheet. However, do you think you could reply here with a full list of the added elements that you want which were after contract please? Ideally split as follows:

- Urgent and need before Sprint 2
- Can be added onto Sprint 2

As you know, we're trying to squeeze ones in, but this would be useful just so I can build out proper time and cost estimates for these, as it may well be we need to do a mini sprint if we can ahead of sprint 2 so you've got the core of what you need for the next set of user testing. 

Thanks!!

**Comment by theharrisonmoore** [comment]
Sure thing.

Urgent and need before Sprint 2:

   - I can flag a piece of content for review by clicking on a Report
   button (user)
   - As a user, I can delete my account (user)
   - I can add text responses (collected from companies via email) to
   profiles (admin)

Can be added onto Sprint 2:

   - I can favourite jobs by clicking on the star button (user)
   - I can view the dates of when the reviews were given (admin)


Can be beyond Sprint 2 if needed:

   - I can change my earwig ID (user)
   - I can edit some or all of the content of a review I have already
   submitted (user)
   - When I send a comment it is sent via email to admin (user)


<https://signup.earwig.work/>

**Comment by thejoefriel** [comment]
Thanks for these @theharrisonmoore - Before we work out the full time estimates, do you think you could please supply mock views for reporting the content? This will make it much clearer for us and then we can more accurately estimate the time.

**Comment by theharrisonmoore** [comment]
Sure thing, I'll do that in a few hours today once I'm back at my computer.

<https://signup.earwig.work/>

**Comment by theharrisonmoore** [comment]
@thejoefriel I've added mockups to Figma for reporting content (see screenshot)
<img width="901" alt="Screenshot 2019-04-22 at 11 28 22" src="https://user-images.githubusercontent.com/45825100/56494271-fb72a000-64f1-11e9-9f5b-fcf5ab3ec4fd.png">

You'll find the list of reasons in a new tab added to the User Stories Sheet: https://docs.google.com/spreadsheets/d/1FYGTogNHkA85wl2gR2NrLbba2Nt5onO6DhI_OoIDSJw/edit#gid=467209501

**Comment by thejoefriel** [comment]
Amazing thanks for doing that so quickly!

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore  - thanks again for sending this across. I've had a meeting to chat through this with the team :)

So as we understand it you would need to receive an email with their message and the page on which they found the inappropriate content?

If this is correct we believe the additional work outlined to be done before sprint 2 would be 2.5 days. Fortunately, we're very much on track with sprint 1 so could complete this by 2nd May I reckon so still ready for the start of your accelerator programme.

In terms of all the other issues, these would be added to sprint 2 and we envisage it needing another 3.5 days as the favourite element would also have an extra part I believe which is that they could sort by their favourites on the job board? And the editing review would require a long user process where they would need to be able to view and click onto each of their reviews and have an edit button to take them into an edit mode for that review. 

So in total this would be 6 additional days work at the same rate we've already been working at - I can email you the exact figure if you like?

Let me know if you think this is workable within your budgets.

Also, while talking about planning, when are you free next week for me to meet and take you through the platform following the first sprint? Ideally tuesday would be great, although we can make it slightly later in the week if you'd prefer us to do those additional features first.

**Comment by thejoefriel** [comment]
Also on this @theharrisonmoore - for the inappropriate content, if you're able to let us know all the pages the flag icon should be on that'd be great!

**Comment by theharrisonmoore** [comment]
Thanks Joe,

Yes, I would need to receive an email with their reason and message, but
not just the page where the content is; it would have to show the
individual content, ie a comment, a voice comment or an image. I will add a
flag symbol to the wireframes now in all the places it's needed.

That's fine with the sprint timings.

Please do send me an exact quote by email for the extra work. It would be
helpful if you could itemise the quote to show the cost of individual work
packets.

<https://signup.earwig.work/>

**Comment by theharrisonmoore** [comment]
> Also, while talking about planning, when are you free next week for me to meet and take you through the platform following the first sprint? Ideally tuesday would be great, although we can make it slightly later in the week if you'd prefer us to do those additional features first.

@thejoefriel Next Tuesday 30th works for me. How does 9 am sound?

**Comment by thejoefriel** [comment]
Hey, the added stories have all been agreed and we've got a date to meet so closing this issue now :)
