### ISSUE TITLE
Issues when replying as Admin on behalf of a company

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#1032]
When I reply to a worker on behalf of a company, there are the following issues:

1. Users should _not_ be able to "report" responses from companies. At the moment, the Report icon is present and needs to be removed.
2. The verified icon appears beside the company name when it shouldn't.
3. The font size is not quite the same as the workers' reviews. The font size needs to be 15 pt.

**Comment by dupreesi** [comment]
@theharrisonmoore on point 3 to be clear: the font size of an admin reply text should be the same as a worker's overall review text right?

**Comment by theharrisonmoore** [comment]
Simon, yes, that's correct. All body text (including reviews and comments)
should be size 15, regular.

Best,
Harrison Moore
Sparky & Founder
*earwig <http://earwigwork.com>*

ᐧ
