### ISSUE TITLE
Changes to verification pages

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#1057]
@dupreesi @thejoefriel Please can we make the following changes to the worker verification pages.

- [x] Remove 'Add your trade' from verification pages, but keep it on the Your Profile page (workers can still add their trade later if they wish from their profiles).
- [x] Update text above example image.
- [x] Update text in 'Learn more' popup modal.
- [x] Change example image.
- [x] Update 'Upload' button label, and styling.
- [x] Ensure consistency across both mobile and desktop.

<img width="1011" alt="Screenshot 2020-01-22 at 10 23 10" src="https://user-images.githubusercontent.com/45825100/72886170-3f086d80-3d01-11ea-8a5c-7cbe63af3547.png">

**Comment by dupreesi** [comment]
@theharrisonmoore should the cancel button on the Verification page be getting removed? if so how are users navigating back?

**Comment by theharrisonmoore** [comment]
Sorry, I think that got missed out. Please include a Cancel button.

Best,
Harrison Moore
Sparky & Founder
*earwig <http://earwigwork.com>*

ᐧ

**Comment by theharrisonmoore** [comment]
@dupreesi the example photo is missing.
![IMG_0D3C415495F5-1](https://user-images.githubusercontent.com/45825100/72925765-2755d700-3d4b-11ea-9003-08bdcdc7f456.jpeg)

iPhone 8, Safari

**Comment by theharrisonmoore** [comment]
@dupreesi the example photo took several seconds to load. Perhaps the image is too large. I will send you a 72dpi version now…

**Comment by theharrisonmoore** [comment]
@dupreesi this text needs to be centre justified like the rest of it.
![IMG_2CFB9510EE0A-1](https://user-images.githubusercontent.com/45825100/72925951-77cd3480-3d4b-11ea-9cbb-3415ee2ba88b.jpeg)
