### ISSUE TITLE
Review data appears twice in Admin

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#1064]
@thejoefriel Review data appears twice in Admin

<img width="1440" alt="Screenshot 2020-01-24 at 07 46 12" src="https://user-images.githubusercontent.com/45825100/73052756-c975dc00-3e7d-11ea-913c-be000e529960.png">

**Comment by theharrisonmoore** [comment]
@thejoefriel @dupreesi with each new review, data is now being multiplied in Admin. Look see:
<img width="1440" alt="Screenshot 2020-01-26 at 15 16 34" src="https://user-images.githubusercontent.com/45825100/73137351-fd542b80-404e-11ea-9846-917d5565e274.png">

**Comment by dupreesi** [comment]
thanks @theharrisonmoore I fixed this bug just now and will get someone to review and merge
