### ISSUE TITLE
Possible domain interference?

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#107]
@thejoefriel @RamyAlshurafa Hi guys, just wondering, is it possible that the work you're doing with the domain 'earwig.work' on GoDaddy could interfere with my existing landing page URL 'https://signup.earwig.work/'? It's no big deal but it's stopped working and I'm just trying to troubleshoot.

**Comment by RamyAlshurafa** [comment]
sorry to hear that @theharrisonmoore 
actually, we didn't start working on anything related to GoDaddy or the email yet, maybe will start tomorrow. hope you can get it back soon

**Comment by theharrisonmoore** [comment]
@RamyAlshurafa No problem, it must be an issue with the existing domain host
