### ISSUE TITLE
Updated FAQ

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#1078]
Please make the following changes to the FAQ page.

- [x] Remove this question:
<img width="1440" alt="Screenshot 2020-02-11 at 11 16 45" src="https://user-images.githubusercontent.com/45825100/74232114-089a8e80-4cc0-11ea-9388-964947b3f53d.png">

- [x] Remove this question:
<img width="1440" alt="Screenshot 2020-02-11 at 11 18 22" src="https://user-images.githubusercontent.com/45825100/74232235-47c8df80-4cc0-11ea-881e-d362a640d798.png">

- [x] Update this copy:
<img width="1440" alt="Screenshot 2020-02-11 at 11 19 45" src="https://user-images.githubusercontent.com/45825100/74232336-7d6dc880-4cc0-11ea-9872-5f3f78c996c5.png">

- [x] Update this copy:
<img width="1440" alt="Screenshot 2020-02-11 at 11 20 58" src="https://user-images.githubusercontent.com/45825100/74232446-b73ecf00-4cc0-11ea-9955-6f4a24d2abf3.png">

- [x] Ensure hyperlinked contents list is updated to reflect changes.

**Comment by RamyAlshurafa** [comment]
Hey @theharrisonmoore 
just to confirm, I updated this too(it's not on the issue)
![image](https://user-images.githubusercontent.com/34629478/74245068-1b768880-4ceb-11ea-9053-8f40c252627f.png)

**Comment by theharrisonmoore** [comment]
Hi Ramy

Great, thank you! Can you show me a screenshot of the change you made?

Best
Harrison Moore
Sparky & Founder
*earwig <http://earwigwork.com>*

ᐧ

**Comment by RamyAlshurafa** [comment]
@theharrisonmoore 
![image](https://user-images.githubusercontent.com/34629478/74311850-0c3e1c00-4d79-11ea-94b4-079a1aa4f604.png)

**Comment by theharrisonmoore** [comment]
Perfect, thanks!

Best
Harrison Moore
Sparky & Founder
*earwig <http://earwigwork.com>*

ᐧ
