### ISSUE TITLE
Only a maximum of three overall reviews should be visible as Level 0 user

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#1081]
@thejoefriel @RamyAlshurafa Only a maximum of three overall reviews should be visible as Level 0 user. You can see in this video that more than three are visible: https://drive.google.com/open?id=13Zd0ZJSWczsLILNyuZcs5h2K5Dl928Cd

Samsung S6, Samsung Internet

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore I spent quite a bit of time on this as it was working locally and realised that it is working in your version too - it is limited it to three reviews. However one of those reviews from a user includes both a voice message as well as a text message. 

I think this is fine as there shouldn't be a hierarchy between voice and text and a user may want to leave both (which is part of the same review). We can change it in future iterations if you like but this isn't a bug. 

Let me know your thoughts and if you want to add to the product backlog of something to change in future.

**Comment by theharrisonmoore** [comment]
Hi Joe, just to confirm, we sorted this and you can close the issue.

Best
Harrison Moore
Sparky & Founder
*earwig <http://earwigwork.com>*

ᐧ
