### ISSUE TITLE
Admin not receiving email about new signup

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#1082]
@thejoefriel @RamyAlshurafa Admin is not receiving an email about new signups.

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore I've just been looking into this and I'm not sure if we ever hard an email about a new sign up - we had one for when they uploaded a photo for you to verify which currently we don't need. 

Can you send me the copy of what this email would say and what email address it should be sent to? That way I can double check and either way, make sure it's set up and working.

**Comment by theharrisonmoore** [comment]
Hi @thejoefriel , you may be right.

The email just needs to be sent to: hello@earwig.work, and say:

Subject: Someone just signed up to earwig
Body: Someone just signed up to earwig with email: [insert email]
