### ISSUE TITLE
Agree database schema

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#11]
Please try building models and paste in here along with your thinking

**Comment by RamyAlshurafa** [comment]
User
Email
Password
trade
photo: image name, image URL
verified: true /false
random ID: 
points: counter
----------
helpful {
commentID
helpedUserID
reviewOwner
}

**Comment by RamyAlshurafa** [comment]
```js
{
  reviewedID: {
    type: ObjectID,
    ref: "company",
  },
  workPerod: {
    from: {
      type: Date,
      required: true,
    },
    to: {
      type: Date,
      required: true,
    },
  },
  reviewer: {
    type: ObjectID,
    ref: "users",
  },
  rate: {
    type: Number,
    required: true, // need validation min and max
  },
  overallReview: {
    type: String,
    required: true,
  },
  voiceReview: {
    name: {
      type: String,
      required: false,
    },
  },
  linkURL: {
    type: String,
    required: false,
  },
  createdAt: {
    type: Date,
    default: Date.now(),
  },
  updatedAt: {
    type: Date,
    default: Date.now(),
  },
  answers: [{
    question: {
      type: ObjectID,
      ref: "answers.questions",
    },
    answer: {
      type: "any",
    },
    comment: {
      type: String,
      required: false,
    },
  }],
  isVerified: {
    type: Boolean,
    default: false,
  },
  worksiteImage: {
    name: {
      type: String,
      required: false,
    },
    linkURL: {
      type: String,
      required: false,
    },
  },
};
```

**Comment by amusameh** [comment]
```js
const QuestionsSchema = new Schema({
  target: {
    type: String,
    required: true,
  },
  questions: [{
    Text: {
      type: String,
      required: true,
    },
    type: {
      type: String,
      enum: ["options", "openText", "number", "multiSelect"]
    },
    options: {
      type: [String],
      required: true,
    },
    subText: String,
    questionID: {
      type: Schema.Types.ObjectId,
      required: true
    }
  }]
})
```

**Comment by RamyAlshurafa** [comment]
```js
name: {
  type: String,
  required: true,
},
category: {
  type: String,
  enum: ["company", "agency", "payroll", "worksite"],
},
phoneNumber: String,
email: {
  type: String,
  unique: true,
},
websiteURL: String,
loacation: {
  lat: Number,
  long: Number,
},
contractor: {
  name: String,
  logoTitle: {
    type: String,
    required: false
  },
  logoUrl: {
    type: String,
    required: false
  }
}
```

**Comment by RamyAlshurafa** [comment]
**Job**

```js
  title: {
    type: String,
    required: true
  },
  trade: String,
  rate: Number,
  hours: Number,
  createdAt: Date,
  startDate: Date,
  description: String,
  company: {
    type: objectId,
    ref: "companies"
  },
  agency: {
    type: objectId,
    ref: "companies"
  },
  worksite: {
    type: objectId,
    ref: "companies"
  },
  favorites: [
    {
      user: {
        type: objectId,
        ref: "users"
      }
    }
  ],
  location:String
```

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa in Users, what is the avatar name and url? I don't believe they will have a profile pic as we will be keeping them anonymous

Also, what were our thoughts on making sure we keep this absolutely secure so sensitive data about the users isn't at risk of getting leaked? Is it worth separating out the users model slightly? Not sure if this would really make a difference is someone got into the database. @Jbarget What are your thoughts on this? Harrison is very keen that we minimise chance of information about the users/reviewers gets into the public as construction companies can (even if illegal) be known to put them on a blacklist

**Comment by RamyAlshurafa** [comment]
@thejoefriel , for the avatar it's for verification processes and will store the url and the photo name from the firestore so we can update/delete that photo

**Comment by amusameh** [comment]
### Questions collection
```js
const questions = {
  id: mongoId,
  number: Number, // each org has serial questions order
  type: String, // yesno, checkbox, ... 
  text: String,
  helper: String,
  isJumping: Boolean,  // yes if there is questions to skip based on the answer
  options: [{
    value: String, // yes, no, ... 
    nextQuestion: Number, // self reference
  }],
  orgType: String, // company agency ....,
};
```

**Comment by amusameh** [comment]
### Answers collection
```js
const answers = {
  question: ref(questions),
  answer: any,
  comments: ref(comments),
  user: ref(user),
  review: ref(review),
};
```
### Comments collection

```js
const comments = {
  organization: ref(organization), 
  question: ref(questions),
  user: ref(user),
  text: String,
};
```

**Comment by thejoefriel** [comment]
This looks good to me. @Jbarget - if you get a chance it'd be great if you could review this at some point today so we can then go ahead and start building the database at the start of next week. Thanks!!

**Comment by Jbarget** [comment]
- all things that end with `id` should be camelCase too eg. `userId`
- `randomID` on the User should just be `userId` and when making requests to do things we should be checking the `userId` and not the `email`. Email should only be used to log in and send emails to.
- `  type: String, // yesno, checkbox, ... ` yes & no is the same as `true` & `false` which is the same as a checkbox
- what is `helper` on a question?
- could there be trade specific questions? which would mean questions have a `tradeId` on them?
- `avatar: { avatarName, avatarUrl }` - I saw the comments above but not sure what this is for, I imagine it could be named better


```
reviews
{
  organizationID: {
    type: ObjectID,
    ref: "company"
  },
```

should the above be `ref: "organisations"`?

**Comment by thejoefriel** [comment]
Thanks @Jbarget 

- There isn't trade specific questions at the moment (it's only split per organisation)
- Helper is additional text that might be included below the question to give the user more information
- Yes you're right about it needing to ref organisations - thanks for the spot! 
- Is yes no a radio input though vs checkbox where you can select multiple options?

**Comment by Jbarget** [comment]
1. all good then 👍 
1. maybe rename to `hintText`
1. no problem
1. you're correct, sorry :)

**Comment by thejoefriel** [comment]
Thanks @Jbarget !

Also @RamyAlshurafa @amusameh - before you set up database tomorrow, we need to add one more field to the organisations schema

We need a 'lastViewed' which stores the date the last time someone viewed their profile

**Comment by RamyAlshurafa** [comment]
ok @thejoefriel
