### ISSUE TITLE
I can edit some or all of the content of a review I have already submitted

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#123]
@thejoefriel Here's an explanation of this feature. We can talk about this in more detail if you wish as I know this is a new feature added recently and may still need a bit of thought and clarification. Indeed, this functionality may still be outside the scope of the latest quote you sent me. That's fine. Apologies if it feels like features keep becoming more complex. They are, but it can't be helped as I'm working closely with three lawyers now and their input is invaluable to building an effective product that is also protected from a legal standpoint.

Workers can edit some or all of the content of a review they've already submitted, providing:

- it's within 30 days of giving the review;

- the entity has not responded; and

- the review has not been marked as helpful by any other workers.

**Comment by thejoefriel** [comment]
OK great thanks for this! have labelled with sprint 2 milestone so we can pick this up then.
