### ISSUE TITLE
Location field added to user signup

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#124]
@thejoefriel We need to add a field to capture users' location (town/city) when they sign-up as a Level 3 user. This info would then be displayed alongside their ID and email in the All Users admin view.

I will add this to the wireframes.

**Comment by thejoefriel** [comment]
- [ ] Add input
- [ ] Update user schema
- [ ] Render on edit profile

**Comment by thejoefriel** [comment]
OK @theharrisonmoore I've put in the criteria. If we get time we'll try to work this into this sprint

**Comment by thejoefriel** [comment]
so to clarify @theharrisonmoore - would this be when they go to get verified, not when they first sign up?

**Comment by theharrisonmoore** [comment]
Yes, only when they get verified (Level 3)
<https://earwig.kickoffpages.com/>
