### ISSUE TITLE
As a user, I can delete my account (user)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#128]
- [x] Add Delete My Account link to Edit Profile page
- [x] Remove all user details from database
- [x] Remove all of their reviews
- [x] Remove all of their comments
- [x] Remove from mailing list

**Comment by thejoefriel** [comment]
@theharrisonmoore - are you able to put on the wireframe for Edit Info where you'd like the Delete My Account link to sit please?

**Comment by theharrisonmoore** [comment]
Done
<https://earwig.kickoffpages.com/>
