### ISSUE TITLE
I can add text responses to profiles (admin)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#129]
- [x] I can see a list of all comments for that organisation
- [x] I can add replies to any comment
- [x] When adding a reply I can choose the name to provide so I can label this as the organisation if I wish or from myself

**Comment by RamyAlshurafa** [comment]
Hi @theharrisonmoore 
when the admin chooses to use his identity to reply on the comment, what the displayed name will be? `Admin` or the id like `rHlvhAPFpC`?

**Comment by theharrisonmoore** [comment]
Hi,

Good question. Actually, when Admin replies to comments it will be on
behalf of agencies, payrolls, or companies. They will send me their replies
by email, and I will then copy & paste them into earwig. So, it needs to be
clear that their comments are from them. For example:

Aces Electrical
'Thanks for your review. We are now looking into it and we aim to improve
our practices going forward. Your experiences are very important to us and
we would urge you to continue to give us feedback like this so we can learn
and improve.'

<https://earwig.kickoffpages.com/>

**Comment by theharrisonmoore** [comment]
So, admin needs to be able to include a display name of his choice.

<https://earwig.kickoffpages.com/>

**Comment by RamyAlshurafa** [comment]
thanks @theharrisonmoore
