### ISSUE TITLE
Agree on tech stack and eslint 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#13]
The current plan so far:

Front-end: React, HTML, CSS, Styled Components, Tachyons
Back-end: Node, Express 
Testing: Supertest

Need to agree the best database language we want to use (e.g. mongo, SQL)
Need to agree the best testing for back end. I know Jest can sometimes not play nicely with mongo (although we've not encountered major issues in our combo of the two so far) so just worth considering if worth looking at something else such as Mocha? Jest may still be best as it means we're writing tests in the same language across front and back since react testing uses jest, but just wanted to open to discussion.

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa - saw you have Jest on the codebase PR. So do you think we should stick with Jest for back end testing?

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel  I've just used it to move on, for now, then we can replace it with what we agree here

**Comment by RamyAlshurafa** [comment]
in terms of database, I think MongoDB good in flexibility so we can refactor the as we go
also, I don't mind trying Mocha
Anyway I'm happy with anything else

**Comment by thejoefriel** [comment]
Yeah I'm happy with Mongo for the flexibility and also for the level of mongoose functions which I think will be important for this. @dupreesi @amusameh - are you happy with Mongo for the database option?

Re Jest for now, makes sense. Do you mind doing some research into Mocha to see if it might be more suitable for mongo? Jest has been fine to be honest before, but just want to make sure we're using the best options

**Comment by RamyAlshurafa** [comment]
OK @thejoefriel

**Comment by amusameh** [comment]
@thejoefriel I'm good with Mongo for database 

I like jest so far. but I just read something in mongoose docs that recommend using mocha 

> Because Jest is designed primarily for testing React applications, using it to test Node.js server-side applications comes with a lot of caveats. We strongly recommend using Mocha instead. If you choose to delve into dangerous waters and test Mongoose apps with Jest

https://mongoosejs.com/docs/jest.html

Both of Jest and Mocha have their fans online, so anyone of them will do I think

**Comment by thejoefriel** [comment]
Also, following our chat just now, things to think about:

- Best way to upload/store images (e.g. worker verification photos, worksite photos)
- Best way to store audio files (this is a sprint 2 issue but one maybe worth thinking about now)
- Double opt-in process to ensure GDPR compliance

**Comment by RamyAlshurafa** [comment]
for upload/store images and audio I think firestore provide a good service for file storage https://firebase.google.com/docs/storage/web/upload-files

**Comment by dupreesi** [comment]
I'm fine with Mongo and Mocha. Regarding images we can also use a payed MLab plan if Harrison is up for it.

**Comment by thejoefriel** [comment]
what's the potential cost limits on firestore @RamyAlshurafa ?

**Comment by RamyAlshurafa** [comment]
it gives you a `quota per day` which is 50,000 read request and 20,000 for write/delete request and 1GB.
https://cloud.google.com/firestore/pricing

**Comment by thejoefriel** [comment]
Yeah I think that sounds good @RamyAlshurafa . So that's for free?

@dupreesi - we were talking about Jest vs Mocha yesterday and Mocha takes a lot more time and complexity to set up so we'll probably stick with Jest for now as it's always worked well for us in the past.

**Comment by RamyAlshurafa** [comment]
@thejoefriel not fully free, you have to pay if you exceeded the free quota, but you can use the quota for free
