### ISSUE TITLE
Remove a review question from the Payroll profile

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#133]
@thejoefriel Apologies, but I have spotted a duplicate question that _is_ needed in the Agency profile but _not_ needed in the Payroll profile, and so needs to be removed. The question is:

'What hourly rate were you paid?'

<img width="958" alt="Screenshot 2019-04-25 at 10 44 21" src="https://user-images.githubusercontent.com/45825100/56726953-aa5be980-6747-11e9-8dcb-36038c36906d.png">

I have removed it from the wireframes and the User Stories Sheet.

**Comment by thejoefriel** [comment]
@amusameh - there's a question that needs to be removed from the database. sorry! How problematic is this to do?
