### ISSUE TITLE
Agree on overall file structure and folder/file names

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#14]
Important we are all clear how we want the file structure to be across back and front. e.g. do we have tests in their own test folder or alongside the file they are testing? do we have a Common folder for common components and Pages for other components? etc

Please show the suggested structure via the comments

**Comment by RamyAlshurafa** [comment]
I think `Tempo` file structure was good
- file names 
  * back-end: `camelCase`
  * front-end: `PascalCase`
- test files :
  * back-end: in `__test__` file 
  * front-end: beside the tested component (maybe if the component has many sub-components we can put the test files in a folder in the component folder)

**Comment by thejoefriel** [comment]
This sounds good to me @RamyAlshurafa 👍

**Comment by thejoefriel** [comment]
We should also set up some global styles as well similar to the Connect 5 project, so that we can make the colour variables available throughout the codebase

**Comment by RamyAlshurafa** [comment]
Are you happy to work in `Sass`?
it would give us some strength at this point
what do you think? @thejoefriel

**Comment by amusameh** [comment]
### file structure:
After talking with @RamyAlshurafa we added a few folders and made some small modifications to the server file structure.
- server: 
       - controllers
       - middlewares: to write our own middlewares for (authorization, auth, validation, ... etc)
       - helpers: any helpers functions ( dates functions .. etc) =>  could be called( libs, utils ) 
       - database: 
              - dummyData => fake data for testing and development
              - models: our mongoose models,
              - queries: our custom database queries (Aggregations ... etc)
              - dbConnection.js
        - router: separate folder for routes
        - __tests__

- client: 
       same as the boilerplate
