### ISSUE TITLE
Landing page update (with icons)

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#148]
@thejoefriel 

As discussed, I've created a new wireframe (mobile and desktop) for the earwig landing page. This will take the place of the original first wireframe called 'Login.'

Here is the embed code for the landing page video:

<iframe width="560" height="315" src="https://www.youtube.com/embed/9eBzZOwaTpw?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Here are the icons used on the Landing Page:

earwig logo white: 
![earwig logo white](https://user-images.githubusercontent.com/45825100/56893194-c928eb80-6a79-11e9-8cd0-bce64d09a396.png)

Award 1: https://www.flaticon.com/free-icon/quality_115778#term=award&page=1&position=2

Award 2: https://www.flaticon.com/free-icon/trophy_1530697#term=award&page=1&position=56

Award 3: https://www.flaticon.com/free-icon/medal_1613997

Award 4: https://www.flaticon.com/free-icon/trophy_757261#term=cup&page=1&position=55

**Comment by thejoefriel** [comment]
Thanks @theharrisonmoore 

So criteria is:
- [ ] Landing page following figma wireframe provided
