### ISSUE TITLE
Linking to organisations between profiles

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#158]
There are two questions:

- In Agency: Pays using the following payrolls
- In Payroll: Works with the following agencies

Ideally these would then link to that organisation's profile page if the user clicked on it

However, when giving a review it is possible for the user to add an organisation that does not exist in the database. This does not add them as an organisation (and it shouldn't do so), so there wouldn't be a profile page to link to. 

We need to work out
- How would you get the right organisation id so we can turn it into a link to their profile
- How do we work out which ones have profiles and which ones don't

Please refer to #99 comment in figma for some more background

**Comment by RamyAlshurafa** [comment]
I think we can think in another way
if a worker reviewed an (agency e.g.) and if he choosed to add new payroll in Pays using the following payrolls question, we can add this payroll in database with isActive = false and add ref to this payroll in the answer.
and when we rendering the agency profile will check for payroll if it's activated, if so we can add link for it, else we will show the payroll name without linking.
the payroll will be deactivated, if the admin activate it, then it will be linked
what do you think?
