### ISSUE TITLE
Reviews

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#17]
Hi @theharrisonmoore we're having some issues with your review question flow as we've noticed that they are actually quite interlinked. For example, when reviewing a payroll I'm asked to select an agency at the end. And similarly, if I'm reviewing an agency I'm asked which payroll and then if I did use a payroll I'm asked lots of similar questions to the payroll review (but I'm not asked everything e.g. how happy I was with the payroll)

Few questions:
- If I'm reviewing an agency and the payroll isn't in the list, what happens? Do I have to add the payroll and if so does this then leave this review?
- If I'm reviewing an agency and the payroll is in the list, do the questions I answer get stored onto that payroll's profile as a review also? If so, how do you get around that there are questions in the payroll review that I wouldn't have been shown so wouldn't add to that review. 
- If I'm reviewing a payroll and the agency isn't in the list, what happens?

**Comment by theharrisonmoore** [comment]
Hi @thejoefriel 

1. If the payroll isn't in the list, there would be an option to add the name of the payroll. These newly added names would sit in a list in the back-end. Later, Admin could then refer to this list and create new profiles accordingly.

2. Good spot! My mistake. I've amended the flow chart (https://whimsical.co/CY3c7ofLGBup9R5Fs73BqV)

3. Same as answer to question 1

Let me know if you still have questions

**Comment by thejoefriel** [comment]
Thanks for the quick response @theharrisonmoore 

1. So we would need to create something on your CMS view that would show names mentioned for either payroll or agency that haven't been reviewed and you can then choose to create a profile for them at a later point?

2. Sorry, just to check have you changed this so now if I say I was paid by payroll I don't then get asked any of the questions about the payroll type, whether it was paid when expected?


So just to clarify, if I was reviewing JOE AGENCY, and I said I used TEST payroll, the information I provide would only be relevant/show up in the reviews for the AGENCY - none of that information (e.g. wage) should be applied to the TEST payroll?

Keeping the reviews as separate as possible (so a review on an Agency will purely generate data to be visualised for that Agency and no other organisations mentioned in my review) would definitely be the cleanest option at this stage I think.

**Comment by theharrisonmoore** [comment]
1. Yes
   2. Yes. I understand that this seems wrong but, bear in mind, this takes
   place during an *agency* review. Some agencies pay workers directly but
   most of them use payrolls. If a worker was paid by a payroll, then they
   should be reviewing the payroll separately so as to avoid payroll-related
   answers ending up on the agency profile.

Ideally, earwig would gather information about *both* the agency and the
payroll (and the worksite and the company) all at the same time. But, this
is too much to ask of a worker, so we do it separately for now. It may be
that, in the future, we send prompts to workers who've recently reviewed
agencies to also review the payroll they used during that contract period.

Not ideal but, as you say, keeping things separate is the cleanest way at
this stage.

<https://signup.earwig.work/>

**Comment by thejoefriel** [comment]
Great that makes a lot more sense now, thanks @theharrisonmoore ! :)
