### ISSUE TITLE
Daily Stand Up Log

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#18]
In this issue, at the end of each working day, please add a comment answering the following questions:

### Am I facing any blockers?

**Comment by thejoefriel** [comment]
Date:
Wed 3 April 2019

What issue(s) did I work on today?
#3 

What issue do I plan to work on tomorrow?
Finish #3 and then #5 and #16 

Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
Date:
Wed 3 April 2019

What issue(s) did I work on today?
#6 #8 #11 
What issue do I plan to work on tomorrow?
Finish  #11 then work on #3 

Am I facing any blockers?
No

**Comment by amusameh** [comment]
Date:
Wed 3 April 2019

What issue(s) did I work on today?
#11 with @RamyAlshurafa  and thinking/searching about the best way to apply it
What issue do I plan to work on tomorrow?
Finish #11 then work on #14 ( the general theme )

Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
Date:
Thur 4 April 2019

What issue(s) did I work on today?
#3 

What issue do I plan to work on tomorrow?
#5 

Am I facing any blockers?
No

**Comment by dupreesi** [comment]
Date:
Thur 4 April 2019

What issue(s) did I work on today?
I read over the open issues

What issue do I plan to work on tomorrow?
will start picking up issues on Monday

Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
Date:
Thur 4 April 2019

What issue(s) did I work on today?
#11
What issue do I plan to work on tomorrow?
#12 
Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
Date:
Sun 7 April 2019

What issue(s) did I work on today?
#12 #10  #7 
What issue do I plan to work on tomorrow?
finish #12 then #31 
Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
Date:
Mon 8 April 2019

What issue(s) did I work on today?
#5 

What issue do I plan to work on tomorrow?
#52 

Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
Date:
Mon 8 April 2019

What issue(s) did I work on today?
#31 

What issue do I plan to work on tomorrow?
#26 
Am I facing any blockers?
No

**Comment by dupreesi** [comment]
Date:
Mon 8 April 2019/ Tuesday 9 April 2019

What issue(s) did I work on today?
#32

What issue do I plan to work on tomorrow?
#32 

Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
Date:
Mon 8 April 2019

What issue(s) did I work on today?
#52 

What issue do I plan to work on tomorrow?
#36 

Am I facing any blockers?
Had an issue with the SVGs for the icons we've been given and also on git rebasing the branch - discussing with Justen the potential solutions Tues afternoon.

**Comment by thejoefriel** [comment]
Date:
Tue 8 April 2019

What issue(s) did I work on today?
#36 

What issue do I plan to work on tomorrow?
#36

Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
Date:
Tue 10 April 2019

What issue(s) did I work on today?
#27 

What issue do I plan to work on tomorrow?
finish #27 then will see

Am I facing any blockers?
No

**Comment by amusameh** [comment]
Date:
Mon 9 April / Tue 10 April 2019

What issue(s) did I work on today?
#55

What issue do I plan to work on tomorrow?
#55
Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
Date:
Mon 9 April

What issue(s) did I work on today?
#36 

What issue do I plan to work on tomorrow?
#36 

Am I facing any blockers?
No

**Comment by dupreesi** [comment]
Date:
Mon 15 April

What issue(s) did I work on today?
#32, #33, #34  

What issue do I plan to work on tomorrow?
finish #34

Am I facing any blockers
yes, 2 meetings and flight back to germany

**Comment by thejoefriel** [comment]
Date:
Thur 18 April

What issue(s) did I work on today?
#36

What issue do I plan to work on tomorrow?
Will see what's about when I pick up work again on Tues

Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
Date:
Thur 18 & Sun 21 April

What issue(s) did I work on today?
#68 #69 #70 #71 & #99 
What issue do I plan to work on tomorrow?
finish #99 and then #76 #77 
Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
Date:
Mon 22 April
What issue(s) did I work on today?
#99, #76 #77 
What issue do I plan to work on tomorrow?
#72, then will see
Am I facing any blockers?
No

**Comment by amusameh** [comment]
Date:
Mon 22 April
What issue(s) did I work on today?
#66, #67 + plus editing some of the review related issues
What issue do I plan to work on tomorrow?
#30
Am I facing any blockers?
No

**Comment by dupreesi** [comment]
Date:
Saturday 20 April
What issue(s) did I work on today?
#34
What issue do I plan to work on Monday?
#34
Am I facing any blockers?
No

**Comment by dupreesi** [comment]
Date:
Tues 23 April
What issue(s) did I work on today?
#34
What issue do I plan to work on Monday?
#119 and then see
Am I facing any blockers?
travelling to Berlin tomorrow having to leave my house around 4pm...

**Comment by RamyAlshurafa** [comment]
Date:
Tues 17 June
What issue(s) did I work on today?
#328 
What issue do I plan to work tomorrow?
#329 and then see
Am I facing any blockers?
no

**Comment by amusameh** [comment]
Date:
Monday 17 June
What issue(s) did I work on today?
#267 #199 (done).  (#339, #327) => in porgess as both issues related to mailchimp 
What issue do I plan to work tomorrow?
continue working on #339, #327
Am I facing any blockers?
no

**Comment by thejoefriel** [comment]
Date:
Monday 17 June
What issue(s) did I work on today?
#331, sorting the new wireframes and setting up production version on Heroku

What issue do I plan to work tomorrow?
#335 

Am I facing any blockers?
no

**Comment by dupreesi** [comment]
Date:
Monday 17 June
What issue(s) did I work on today?
#390 and #385 

What issue do I plan to work tomorrow?
finish #385 and then see

Am I facing any blockers?
yes, flying back to Germany in the afternoon

**Comment by RamyAlshurafa** [comment]
Date:
Tuesday 18 June
What issue(s) did I work on today?
#355  #354 #334 #329

What issue do I plan to work on Sunday?
#332 #353 #356

Am I facing any blockers?
Reset password PR is waiting for figma to be done

**Comment by thejoefriel** [comment]
Date:
Tuesday 18 June
What issue(s) did I work on todaY?
Merging prs and admin

Am I facing any blockers?
Issues importing sketch files into figma

**Comment by amusameh** [comment]
Date:
Tuesday 18 June
What issue(s) did I work on today?
 #339, #327
What issue do I plan to work on tomorrow?
#327 => sitting up sentry.io and see then.
Am I facing any blockers?
the figma issue as everyone else.

**Comment by dupreesi** [comment]
Date:
Monday 25th June
What issue(s) did I work on today?
#385 #358 #360 #344
What issue do I plan to work on tomorrow?
#338
Am I facing any blockers?
no

**Comment by RamyAlshurafa** [comment]
Date:
Monday 24th June
What issue(s) did I work on today?
#342
What issue do I plan to work on tomorrow?
finish #342
Am I facing any blockers?
no

**Comment by amusameh** [comment]
Date:
Monday 24th June
What issue(s) did I work on today?
#333 #326 #318 and #316
What issue do I plan to work on tomorrow?
start with #336 and see then
Am I facing any blockers?
no

**Comment by dupreesi** [comment]
Date:
Tuesday 26th June
What issue(s) did I work on today?
#357, #338, #347, #360 
What issue do I plan to work on tomorrow?
#360 and #347
Am I facing any blockers?
no

**Comment by thejoefriel** [comment]
Date:
Tuesday 26th June

What issue(s) did I work on today?
#331 #335 #340 #291 #337

What issue do I plan to work on tomorrow?
Will push up PR and then pick another issue

Am I facing any blockers?
no

**Comment by RamyAlshurafa** [comment]
Date:
Tuesday 25th June

What issue(s) did I work on today?
#342 

What issue do I plan to work on tomorrow?
finish #389, and will see 

Am I facing any blockers?
no

**Comment by amusameh** [comment]
Date:
Tuesday 25th June

What issue(s) did I work on today?
fix issues from the previous PR, #362 
What issue do I plan to work on tomorrow?
#362 
Am I facing any blockers?
no
