### ISSUE TITLE
Randomly generated earwig ID for users?

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#19]
@Jbarget @thejoefriel @dupreesi @amusameh @RamyAlshurafa ,

As you know, workers who get verified will be assigned a unique, randomly generated earwig ID. In the wireframes I sent you I have represented this as MB7466.

Does anyone have any good ideas for random IDs? Has anybody seen examples of this done in a smart or fun way? For example, could we use certain words instead of numbers?\

All ideas welcome!

**Comment by thejoefriel** [comment]
We can generate a short ID relatively simply using a node package like this: https://www.npmjs.com/package/shortid

This would be my main recommendation as it keeps it unique while importantly not getting so long that it becomes a bit unwieldly for design purposes on mobile screens etc.

**Comment by theharrisonmoore** [comment]
Okay. So, will the IDs look like this:

eWRhpRV
23TplPdS
46Juzcyx
dBvJIh-H
2WEKaVNO

On Fri, 5 Apr 2019 at 10:26, Joe Friel <notifications@github.com> wrote:
>
> We can generate a short ID relatively simply using a node package like
this: https://www.npmjs.com/package/shortid
>
> This would be my main recommendation as it keeps it unique while
importantly not getting so long that it becomes a bit unwieldly for design
purposes on mobile screens etc.

**Comment by thejoefriel** [comment]
Yes exactly we can also configure what characters are allowed. So for example we can remove dashes I believe and restrict it to just letters and numbers

**Comment by theharrisonmoore** [comment]
That sounds good. Can we make the IDs 5 characters (including 2 numbers),
with no dashes?

<https://signup.earwig.work/>

**Comment by Jbarget** [comment]
At what point are we thinking to expose the user's `id` to the user?

**Comment by theharrisonmoore** [comment]
The user ID will be visible beside any text/voice review, as well as any
subsequent replies. See designs for reference.

<https://signup.earwig.work/>

**Comment by thejoefriel** [comment]
It's important to clarify that this random ID is purely for show purposes (the same as them having a username) so they have an anonymous identity on the platform. We would also have the unique much longer and more secure ID mongo generates for us which wouldn't be exposed, but which we use as part of the authenticating the user.

**Comment by theharrisonmoore** [comment]
@thejoefriel @Jbarget Yes, the earwig ID is a stand-in for their username. It's important to have an ID for the following reasons:

1. Reviews are linked to the ID
2. Other activities (eg replies, and allocating 'Helpful' points) are linked to the ID
3. Helpful points earned are linked to the ID
4. Users will chat with each other and thus see each others' ID

I'd like to add in the functionality for users to change their ID later, but this needs more thought and might come in in Sprint 2 only if there's the scope.

**Comment by thejoefriel** [comment]
OK all makes sense! Will close this issue for now.
