### ISSUE TITLE
earwig email addresses and their uses

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#198]
@thejoefriel Hi guys, please see this tab in the Google Sheet, which explains the different email addresses and their uses.

https://docs.google.com/spreadsheets/d/1FYGTogNHkA85wl2gR2NrLbba2Nt5onO6DhI_OoIDSJw/edit#gid=680660428

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa - are these in line with what we have in the env file on Heroku?

**Comment by RamyAlshurafa** [comment]
@thejoefriel No, for now, we have `hello` and `report`, need to be updated

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa have we updated these? If so, do you mind closing the issue. Thanks!
