### ISSUE TITLE
Admin keeps receiving daily 'test failed' email

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#200]
@thejoefriel Hi guys, it's not a major problem, but each day I receive the following email:

<img width="1428" alt="Screenshot 2019-05-10 at 10 10 38" src="https://user-images.githubusercontent.com/45825100/57516168-1d4e8e00-730c-11e9-8e12-6c344d78b160.png">

**Comment by RamyAlshurafa** [comment]
I think because of the email `test@testing.com` does not exist

**Comment by theharrisonmoore** [comment]
I see. Thanks Ramy. How do we stop it?

<https://earwig.kickoffpages.com/>

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore - are you still receiving this?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> No, I haven't seen them for a while
now. Thanks!

<https://earwig.kickoffpages.com/>
