### ISSUE TITLE
Page loads partly scrolled down, so that the title isn't fully visible

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#204]
This is across the entire app generally

**Comment by thejoefriel** [comment]
This has been fixed on the majority of devices but is still playing up on iphone for some reason!

**Comment by dupreesi** [comment]
I can't replicate this bug @thejoefriel...

**Comment by theharrisonmoore** [comment]
@Simon Dupree <simon@yallacooperative.com>  Here is a video showing this
bug in action:
https://drive.google.com/file/d/1EmTc0ntDmyLRJEWiJwhc-9EJ9PApNj7m/view?usp=sharing

<https://earwig.kickoffpages.com/>

**Comment by dupreesi** [comment]
@theharrisonmoore thanks for that!
