### ISSUE TITLE
It won't let me click to pre-load the email field with addresses saved in my phone

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#207]
When you're given suggested emails on your phone, it doesn't then pre-fill the form with these.

**Comment by dupreesi** [comment]
@thejoefriel is this at the login/ sign-up? I cannot replicate this bug on my Samsung A7.

**Comment by theharrisonmoore** [comment]
@Simon Dupree <simon@yallacooperative.com> it was when I was trying to sign
up (using iPhone SE)
<https://earwig.kickoffpages.com/>

**Comment by thejoefriel** [comment]
This is a common issue with iPhone and Chrome: https://github.com/facebook/react/issues/1159

It doesn't prevent the user from entering details manually and getting logged in so changing this to a refactor where we will stop using Formik on login/signup to add autocomplete options across all browsers

**Comment by theharrisonmoore** [comment]
@thejoefriel @dupreesi I no longer have this issue. I can do it!
