### ISSUE TITLE
When I click to Edit my verification photo, it lets me take/upload a new photo, but then nothing else happens (ie I can't update my trade, and I don't get a notification. Admin doesn't receive notification either.

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#209]
@theharrisonmoore - we're looking into this photo issue why the notification isn't being sent. However, in terms of editing the trade, that wasn't a user story or something shown in the wireframes either? Are you saying if they edit their photo it changes their trade?

**Comment by theharrisonmoore** [comment]
Hi @thejoefriel, yeah, apologies it wasn't in the user stories. I think it
needs to be. Happy for this to be added to Sprint #2 if you are?

<https://earwig.kickoffpages.com/>

**Comment by theharrisonmoore** [comment]
@thejoefriel When a user clicks 'Edit Verification Photo,' they need to be taken to the normal Get Verified page. That's all.

**Comment by dupreesi** [comment]
@thejoefriel @theharrisonmoore we are currently working on the edit verification photo bug so that a user can upload a new pic. Regarding admin notifications - we are not aware that the admin should be getting emailed after someone uploads a (new) photo. the original issues #27 and #71 also don't involve this. Are we missing something?

**Comment by theharrisonmoore** [comment]
@dupreesi @thejoefriel I am _really_ sorry about this but I have made a mistake. I did not think through this verification aspect well enough. My old thinking was that we ought to give workers the ability to go through the verification process again. But now that I've properly thought through the implications of this (eg Would Admin need to verify/reject them again? What happens to their existing reviews while this happens?), it's clear that it creates more problems than it solves.

Could we remove this ability altogether from the Edit Profile page?

I'm _really_ sorry about this. I know you've already spent time on it and I should have thought more carefully through it. I'm doing my best but I'm afraid I've been so busy that I screwed up.

Any questions or suggestions please let me know.

**Comment by dupreesi** [comment]
@theharrisonmoore done!
