### ISSUE TITLE
Cookies?

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#21]
@thejoefriel Could you tell what we do about Cookies, if and how they affect users of earwig? I'll have to prepare a Cookies Policy to ask users to consent to cookies, which I assume would pop-up as a banner when they first visit the site?

**Comment by thejoefriel** [comment]
We will use a cookie to determine if the user is logged in. For google analytics it depends on how deep you want the tracking to be. At a basic usage (seeing pageviews etc) it is possible you may not need to get consent, it's just if you are collecting/using personal data. There's more information on it here: https://www.jeffalytics.com/gdpr-cookie-consent-google-analytics/

@Jbarget - would we need to provide a cookie disclaimer pop-up do you think?

**Comment by theharrisonmoore** [comment]
I would like to use Google Analytics.

<https://signup.earwig.work/>

**Comment by Jbarget** [comment]
![image](https://user-images.githubusercontent.com/11725595/55624505-71fb6800-57a6-11e9-97b3-6d671c924d00.png)

this seems like a good summary, completely appreciate that this development time would not have been factored into time estimates and scoping

**Comment by thejoefriel** [comment]
The cookie we are using for the process of keeping track of whether they are logged in appears to be exempt and so we do not need a disclaimer for this bit :

> The European Commission’s official Internet Handbook lists the cookie types that are “clearly exempt from consent”, including:

> User‑input cookies (session-id) such as first‑party cookies that keep track of the user's input when filling in online forms, shopping carts, etc., for the duration of a session or persistent cookies limited to a few hours in some cases
Authentication cookies, which identify the user once they have logged in, for the duration of a session
User‑centric security cookies, used to detect authentication abuses such as multiple failed login attempts, for a limited persistent duration
Multimedia content player cookies, used to store technical data to play back video or audio content, for the duration of a session
Load‑balancing cookies, which help distribute server requests evenly to keep service running smoothly, for the duration of session
User‑interface customization cookies such as language or font preferences, for the duration of a session (or slightly longer)
Third‑party social plug‑in content‑sharing cookies, for logged‑in members of a social network


So the only bit we would need a disclaimer for would be Google Analytics. This may need a banner depending on how you're using Google Analytics. There are lots of details on it for you @theharrisonmoore  here: https://www.cookiebot.com/en/google-analytics-gdpr/

As Google Analytics isn't implemented until the second sprint, I'd suggest we both review these resources and then check back in to discuss this at the point we do planning for the second sprint?

Also, looking at GDPR rules, if a user chooses to delete their account, we have to remove it from the database so you would not be able to still have this data.

**Comment by theharrisonmoore** [comment]
Right on all counts. Let's revisit these issues in Sprint #2.

Yes, for GDPR we must have a user-delete feature for the 'right to be
forgotten.'

PS: I have a Cookie Policy already written, which would need to be updated
based on our approach.
<https://signup.earwig.work/>

**Comment by theharrisonmoore** [comment]
@thejoefriel Here's an update on Cookies.

The Cookies Policy outlines the use of five Cookies (one for determining if users are logged in, and the other four are for Google Analytics, which we will implement later).

The site needs to have a Cookies banner. In terms of styling, just go for a banner at the bottom of the page (desktop) and a pop-up (mobile). Exactly like this:

<img width="1440" alt="Screenshot 2019-05-09 at 11 19 15" src="https://user-images.githubusercontent.com/45825100/57446350-64754a00-724c-11e9-9dc6-cd44402732c9.png">

**Comment by thejoefriel** [comment]
Thanks for clarifying @theharrisonmoore 

I believe we would just use JWT for this as well to have consistency. @RamyAlshurafa - what do you think? This is for creating a cookie that will remember the user has been on the website before and therefore seen the cookie disclaimer banner (so we don't show it to them every time they go on the website)

**Comment by RamyAlshurafa** [comment]
@thejoefriel 
so for not logged in users we will display the banner once? so if the user closed the app and open it again he will not see this again?

**Comment by Jbarget** [comment]
Ironically this would normally be done with a cookie
