### ISSUE TITLE
When submitting a report, it fails and shows error message 'Cannot read property 'eserid' of undefined'

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#210]
I can't replicate this issue myself - it works for me - but video of the issue Harrison encountered below: https://drive.google.com/file/d/1SfrdzWu9Z-btyGXOqRrFtEjFkdUAi5Ex/view

**Comment by RamyAlshurafa** [comment]
went through the same steps and the same profile in the video and the bug didn't appear

**Comment by dupreesi** [comment]
neither was it possible for me to replicate this bug. @theharrisonmoore could you please check if it still appears on your device?

**Comment by theharrisonmoore** [comment]
@dupreesi <https://github.com/dupreesi> I cannot either.

I'll let you know if I see it again.

<https://earwig.kickoffpages.com/>

**Comment by thejoefriel** [comment]
Just closing this for now, but will reopen if the bug re-emerges!
