### ISSUE TITLE
Didn't check is still being treated as if yes

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#215]
- On Payroll profile under 'Payslips are easily accessible', the data bar show data, but I selected 'I didn't check' when giving the review

- On Worksite profile under 'Public transport within 10 mins walk', the data bar shows data, but I selected 'I don't know' when giving the review

- On Worksite profile under 'Toilets are well maintained', the data bar shows data, but I selected 'I didn't check' when giving the review

- On Worksite profile under 'Shops for hot food within 10 mins', the data bar shows data, but I selected 'I didn't check' when giving the review

- On Worksite profile under 'Canteen is heated', the data bar shows data, but I selected 'I didn't check' when giving the review

**Comment by theharrisonmoore** [comment]
@thejoefriel @dupreesi I gave two reviews to a new profile - the first review I chose 'I didn't check' for every possible answer; the second review I chose 'Yes' - and the data bar shows a 50/50 distribution.

<img width="1423" alt="Screenshot 2019-05-28 at 17 24 00" src="https://user-images.githubusercontent.com/45825100/58494787-cea74d80-816d-11e9-9f1e-53146343f6c1.png">
