### ISSUE TITLE
Separation between worker email and worker activity

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#22]
@thejoefriel Hi Joe, did you manage to think of a way to ensure worker emails are not able to be connected to any review activity in the event the earwig database is compromised? I know we touched on it, but I will need to understand the strategy and have something in writing from you that I can then use to back up my explanation to stakeholders, as well as to inform earwig's promotional conversation with workers. It'll be the first question they ask, and if I don't have a straight answer with evidence to back it up, they won't even sign up. It's really important.

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore . So we've pulled together the database schema now. The database will be a mongo database hosted on mLab which is the main cloud database for mongo database structures. 

The only way to access the database would be via a log in to mLab that you will be given. There are full details on mLab's security here: https://docs.mlab.com/security/
The log in details will not be included in any of the codebase, and the only other place it is stored is part of the environment variables on Heroku. Again Heroku will have one log in that you will be given. And there's full details on Heroku's security here: https://www.heroku.com/policy/security

For the platform to work, users have to be linked to reviews within the database. So while this is not shown on the platform at all, technically if someone did get into the database they could get hold of this information. 

The services we are using are very secure by the nature of their services and are definitely the best practice we would use for an initial MVP like the one we're building. To increase security any further, we would need probably an entire sprint on its own to properly research additional security measures and carry out implementation.

I hope that makes sense and is all ok. As we've discussed before, while we're aiming to build this in a way that can scale, for the timeframe and budget currently scoped, this is very much a MVP designed to enable you to carry on user testing and start bringing on board users. Further sprints would be really needed to assess these sorts of areas when you're starting to talk about the platform catering for users and activity at a truly mass scale.

**Comment by theharrisonmoore** [comment]
Loud and clear. Thanks for this. I'm happy to go ahead with the schema
you've planned.

<https://signup.earwig.work/>

**Comment by theharrisonmoore** [comment]
"So while this is not shown on the platform at all, technically if someone did get into the database they could get hold of this information." > But it would only be their email address, right? They're not giving any other identifiable information to earwig.

**Comment by thejoefriel** [comment]
The only other piece of information is their trade id I believe and their trade?

They obviously upload a verification photo, but as soon as you approve it that then gets deleted.
