### ISSUE TITLE
Turning the car parking cost question into a slider

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#227]
@thejoefriel As discussed, we'd like to turn the question 'How much did car parking cost?' into a slider for users, ranging from zero > £50+ (increasing in increments of £1).

Please can you let me know:
1. Can this fit in Sprint 1 or will it be in Sprint 2?
2. Do you need me to sketch the UI in Figma?

**Comment by thejoefriel** [comment]
User story created now: https://github.com/yalla-coop/earwig/issues/334
