### ISSUE TITLE
Search bar functionality: spaces between characters, and words in different orders

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#230]
@thejoefriel Could we discuss the best way to ensure the following:

1. Users can still find the profile they're searching for irrespective of if they add or don't add spaces between characters (eg S E S or SES)?
2. Users can still find the profile they're searching for irrespective of the order in which they write words (eg Paddington Crossrail or Crossrail Paddington)?

**Comment by theharrisonmoore** [comment]
@thejoefriel @dupreesi I have gone through the databases and removed spaces between characters. Here are the updated databases:

[agencies.xlsx](https://github.com/yalla-coop/earwig/files/3227058/agencies.xlsx)
[companies.xlsx](https://github.com/yalla-coop/earwig/files/3227059/companies.xlsx)
[payrolls.xlsx](https://github.com/yalla-coop/earwig/files/3227061/payrolls.xlsx)

**Comment by dupreesi** [comment]
@theharrisonmoore thanks! 
regarding the search functionality: 
We've slightly improved the flexibility of the current search experience.
Now a user can start typing in any word/ letters and it will find all related entries: e.g. Crossrail will show you Paddington Crossrail (and all other related entries to Crossrail). So its not only matching precisely the letter by letter giving the user a bit more room to filter stuff...
BUT: When I type Crossrail Pa... or C R O S ... then nothing gets shown currently which of course can be improved. 
Please try it and let us know what you think. It will be active shortly (in like 1h..).

Generally: When the search needs to be more intelligent (e.g. remove whitespaces but still being able to know when a second word starts etc.) we might need to shift to a more advanced package which is usually not free of charge. Programming such search engines on your own takes forever as there are so many cases to be considered. Thats why the code will become quite complicated and hence free packages only provide limited abilities to search databases (like the one we are using now). Lets discuss this as part of our next meeting which I'm sure @thejoefriel will put in the diary as soon as he is back in the UK (next week).

**Comment by theharrisonmoore** [comment]
@Simon Dupree <simon@yallacooperative.com> Thanks, I will give it a go
shortly.

I just tried to log in as Admin and I think the credentials have
disappeared. Could you give me the following new Admin login credentials:

Username: earwigadmin
Password: Phuket2016e

<https://earwig.kickoffpages.com/>

**Comment by amusameh** [comment]
@theharrisonmoore  Please be careful from sharing private info in GitHub as it's not private. you can use email for private stuff

**Comment by dupreesi** [comment]
new login sent via email @theharrisonmoore

**Comment by theharrisonmoore** [comment]
Whoops, good point. I had forgotten about that. Thanks for the heads up!

<https://earwig.kickoffpages.com/>

**Comment by theharrisonmoore** [comment]
Thanks, Simon.

<https://earwig.kickoffpages.com/>

**Comment by theharrisonmoore** [comment]
Hi Simon,

After a quick play with the search, it doesn't work in the way it needs to
work. As you said, if we type 'Crossrail Paddington' we get the profile.
But we do not get it when we type 'Paddington Crossrail.' This was always
the original issue we were having.

It's crucial this is solved because otherwise, we'll very quickly have
situations where some workers search one way and find the profile, while
others search another way and then create a new profile. Apart from this
being an administrative problem for us on the back-end, it will also mean
that later workers will find duplicated profiles and won't know which
profile to use.

Also, all of the profile names (agencies, payrolls, worksites, and
companies) no longer have capitals, which looks odd.

PS: This morning I put the updated databases on GitHub, which have had all
the spaces between letters removed.

<https://earwig.kickoffpages.com/>

**Comment by dupreesi** [comment]
The issue with no capitals should be fine now.. please check again . 

Regarding the search functionality I believe that we need to meet in order to discuss exact search requirements which we can certainly implement in sprint 2. 
We can then show you different packages. For now: do you prefer that we are restoring the search bar to the original version (so you would need to type in the exact order) or should we leave it as it is (it would find paddington crossrail by typing crossrail or paddington) until sprint 2?

> Am 28.05.2019 um 15:43 schrieb Harrison Moore <notifications@github.com>:
> 
> Hi Simon,
> 
> After a quick play with the search, it doesn't work in the way it needs to
> work. As you said, if we type 'Crossrail Paddington' we get the profile.
> But we do not get it when we type 'Paddington Crossrail.' This was always
> the original issue we were having.
> 
> It's crucial this is solved because otherwise, we'll very quickly have
> situations where some workers search one way and find the profile, while
> others search another way and then create a new profile. Apart from this
> being an administrative problem for us on the back-end, it will also mean
> that later workers will find duplicated profiles and won't know which
> profile to use.
> 
> Also, all of the profile names (agencies, payrolls, worksites, and
> companies) no longer have capitals, which looks odd.
> 
> PS: This morning I put the updated databases on GitHub, which have had all
> the spaces between letters removed.
> 
> <https://earwig.kickoffpages.com/>
> 
>

**Comment by theharrisonmoore** [comment]
Hi Simon,

Yes, I think we need to sit down together and discuss the search bar.
Thanks for your help on this. Let's leave it as it is for now. You can see
from this video where the challenges are:
https://www.loom.com/share/9737b9d9050242fe995c7f0b50dde567

Thanks for adding capitals back to the names. Sorry to be a pain, but it
has only added capitals to the first letters of each word, whereas before,
the capitals were consistent with the databases I'd prepared. For example,
there are plenty of examples of names like *AAA Scaffolding* that now say *Aaa
Scaffolding*. It wasn't like this before. Please refer to the four
databases I gave you. It may seem trivial, but little things like this will
go along way to winning credibility amongst users.

<https://earwig.kickoffpages.com/>

**Comment by dupreesi** [comment]
@theharrisonmoore yeah totally get that and for a production-level app that has a central search function this should totally be getting integrated. So the best option is to look into payed plans for website search packages such as https://www.algolia.com/. When in production it is also recommended to integrate some sort of analytics so you can track user's search journeys and improve hereby earwig's search experience/ SEO. 
we'll sort out the capital bug!

**Comment by theharrisonmoore** [comment]
@Simon Dupree <simon@yallacooperative.com> Can you tell me what
production-level app means?

I have looked at Algolia and I would be happy to use it, providing it
didn't affect the rest of the app in any way. Although, at $29-499 per
month, I'm not sure this is a tenable solution on the budget I have.

<https://earwig.kickoffpages.com/>

**Comment by dupreesi** [comment]
@theharrisonmoore we can look into more solutions. maybe we can find something cheaper. production level code is quite subjective but basically in our case it means going away from the Minimum Viable Product to something that will be going live with multiple users aiming towards constant improvement in terms of
- error handling
- edge case condition handling
- improve portability to multiple platforms
- well thought out naming of variables, functions, methods, classes, parameters etc
- increased testability
- sufficient documentation
- optimisations for code space or speed (-> refactoring)
- user interface considerations (e.g. search, SEO ...)
In general:
All of those points require time and continuous testing, discussions. You can't go live with a product thats perfect but obviously it should not crash all the time/ major bugs should be removed etc...

**Comment by theharrisonmoore** [comment]
I see, thanks. Okay, well let's set up a meeting with you, Joe and me. I've
asked Joe about the 4th June. What's you availability like that week?

<https://earwig.kickoffpages.com/>

**Comment by dupreesi** [comment]
I'm gonna be in the UK June 12-18 but could join remotely on June 4th ?

**Comment by theharrisonmoore** [comment]
@Simon Dupree <simon@yallacooperative.com> Yes, let's aim for the morning
of the 5th June. You could join remotely if you're available then?

<https://earwig.kickoffpages.com/>

**Comment by dupreesi** [comment]
@theharrisonmoore all major bugs should be resolved by now and the new organisations will be updated today. 
June 5th works for me!

**Comment by theharrisonmoore** [comment]
@Simon Dupree <simon@yallacooperative.com> Thanks! Will I need to register
myself again?

<https://earwig.kickoffpages.com/>

**Comment by dupreesi** [comment]
@theharrisonmoore no you should be able to login with the same creds..

**Comment by theharrisonmoore** [comment]
Gotcha

<https://earwig.kickoffpages.com/>
