### ISSUE TITLE
Clicked buttons must show users progress is being made

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#231]
@thejoefriel As discussed, we're having issues with multiple feedback and reporting being sent to Admin because users cannot tell if buttons they've clicked on have registered the click. Can the buttons pop, click, change colour or otherwise show progress is being made to alleviate this issue?

**Comment by thejoefriel** [comment]
Issue has been created for this https://github.com/yalla-coop/earwig/issues/365
