### ISSUE TITLE
Adding a 'Cancel this review' button to the review-giving process

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#232]
@thejoefriel We talked about this a few weeks back but then it slipped my mind. We need to add a 'Cancel this review' so users can cancel if they wish.

Can you let me know:
1. Can this fit in Sprint 1 or will it be Sprint 2?
2. Do you need me to add this to the UI in Figma?

**Comment by thejoefriel** [comment]
User story issue created for this #332
