### ISSUE TITLE
Date input should only go back 12 months max.

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#234]
@thejoefriel I failed to include this is the User Stories, but we need to make sure users can only go back as far as 12 months when they're selecting dates.

Can you let me know:
1. Can this fit in Sprint 1 or will it be Sprint 2?
2. WIll there need to be a bit of copy for a pop-up when users try to go back further than 12 months? Or can this be self-explanatory?

**Comment by thejoefriel** [comment]
This will be integrated into sprint 2
