### ISSUE TITLE
Add a link to the Review Submission Thank You page

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#236]
@thejoefriel I failed to include this in the User Stories, but once a user has given a review and is on the Thank You page, we need to add a link to take the user back to the entity they just reviewed.

The link should say: Go back to …

Can you let me know:
1. Can this fit in Sprint 1 or will it be Sprint 2?
2. Do you need me to add this into the designs in Figma?

**Comment by thejoefriel** [comment]
User story issue has been created for this #333
