### ISSUE TITLE
earwig holds data containing the names of individuals (supervisors & reps)

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#24]
It just occurred to me that part of the review process gives workers the opportunity to submit the names of certain supervisors on site, as well as reps working at agencies, and payrolls.

This data is obviously sensitive. If you look at the 'inputs and outputs' tab of the User Stories Sheet, you'll see that this data isn't rendered in the platform. However, we are collecting this data because it is valuable to the companies, who will eventually pay to access this data.

We need to ensure the names of these individuals are not publically accessible under any circumstances. Having read the database schema and looked at the security documentation from mLab, I'm sure it'll be fine. But I just wanted to flag this issue in case you guys can foresee any challenges because of it.

**Comment by thejoefriel** [comment]
That's fine. We're not showing that on the front so it will be as secure as the users' own information. Definitely in future sprints it would be good to dedicate time to really looking at optimising the security.
