### ISSUE TITLE
Users can give reviews even before they've been verified

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#240]
@thejoefriel As discussed, users who upload a verification photo will be doing so because they wish to give a review. At the moment, they would have to wait until Admin has verified them. But this creates a blockage and encourages users to leave the site frustrated at not having been able to give a review.

Therefore, we need to give them the option to give reviews as soon as they've uploaded a verification photo. These reviews will be collected but not rendered. Once Admin has verified the user, any reviews they gave in the interim will then be rendered.

I've added this to the Access Levels tav here: https://docs.google.com/spreadsheets/d/1FYGTogNHkA85wl2gR2NrLbba2Nt5onO6DhI_OoIDSJw/edit#gid=1173862825

Joe, this enhancement is a priority.

**Comment by thejoefriel** [comment]
User story issue created for this #330
