### ISSUE TITLE
Adding Terms, Privacy, Cookies, and Guidelines to the site

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#241]
@thejoefriel Here are the finished Terms of Use, Privacy Policy, Cookies Policy, and Community Guidelines to be added to the site in the Privacy & Terms page.

Each document needs to sit on its own page, so on the Privacy & Terms page, we can display a simple list of items, which when clicked open the appropriate page in a new window.

If you need me to create a wireframe for this please let me know.

[earwig - Community Guidelines.pdf](https://github.com/yalla-coop/earwig/files/3191154/earwig.-.Community.Guidelines.pdf)
[earwig - Terms of Use.pdf](https://github.com/yalla-coop/earwig/files/3191155/earwig.-.Terms.of.Use.pdf)
[earwig - Privacy Policy.pdf](https://github.com/yalla-coop/earwig/files/3191156/earwig.-.Privacy.Policy.pdf)
[earwig - Cookies Policy.pdf](https://github.com/yalla-coop/earwig/files/3191157/earwig.-.Cookies.Policy.pdf)

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore - yeah do you mind creating wireframes please?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Done.

<https://earwig.kickoffpages.com/>
