### ISSUE TITLE
Website speed and page loading issues

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#242]
Pages often take more than ten seconds to load. More than half the time, they don't load at all. This seems to be particularly on Harrison's computer and I've seen it in person, but struggle to replicate on our own devices. 

Video here: https://drive.google.com/file/d/17VNXduvLqVlOmfNWlQvtZTDnMLZsbfP5/view?usp=sharing

Maybe worth investigating that there's no obvious bugs here we're missing?

**Comment by dupreesi** [comment]
@theharrisonmoore we hope that the lastest updates will resolve this issue! Please let us know if thats not the case

**Comment by theharrisonmoore** [comment]
Okay thanks, will do!

<https://earwig.kickoffpages.com/>

**Comment by thejoefriel** [comment]
Hey, just closing this for now, but like the others we can reopen if the problem re-emerges. :)
