### ISSUE TITLE
Review: On a few questions the text box is buggy and shows only half of the characters. It also needs to show a £ before the figure

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#263]
'What hourly rate were you paid?' - Agency
'How much were you charged?' - Agency
'How much were you charged for payroll?' - Payroll

**Comment by amusameh** [comment]
@thejoefriel  can you explain more? maybe a screen shot if that's possible?

**Comment by dupreesi** [comment]
yes @theharrisonmoore a picture/ video on this bug would be really helpful as we cannot replicate this bug... thank you!

**Comment by theharrisonmoore** [comment]
@dupreesi <https://github.com/dupreesi> Please hold-off on addressing this
bug for now. I think you, Joe and I are going to have a meeting about some
amendments including replacing all number text boxes with sliders.

<https://earwig.kickoffpages.com/>

**Comment by dupreesi** [comment]
ok @theharrisonmoore let's do that.
