### ISSUE TITLE
Adding Intercom, Sentry, Satismeter, Hotjar, and MixPanel

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#269]
@thejoefriel Hi Joe, totally appreciate none of this (bar Google Analytics) was in the spec, but having had a session with Bethnal Green this week, it's clear that we'll need to integrate the following third-party apps:

Zendesk (for quick learning and responding proactively to users on the site who have issues)
Sentry (for bugs on the front-end)
HotJar or LogRocket (for seeing user sessions)
MixPanel (for more advanced analytics so we can track visitor > signup conversions; number of reviews; number of comments, etc.)

I'm happy to do all the leg work regarding pricing and learning how to use the platforms. But will need your help with the technical integrations. Can you let me know a good time to do this?

Thanks, Joe

**Comment by thejoefriel** [comment]
Issue created for this #327
