### ISSUE TITLE
rebuild database

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/earwig#280]
@theharrisonmoore in order to update the app with the latest fixes we would need to re-build the production database. This means that all data on the app will be lost. Would that be alright or do you need us to back stuff up?

**Comment by theharrisonmoore** [comment]
@Simon Dupree <simon@yallacooperative.com> No problem, all the data on
there is just dummy data at the moment.

Question: will the database be wiped every time there's an update?

<https://earwig.kickoffpages.com/>

**Comment by RamyAlshurafa** [comment]
@theharrisonmoore 
we do that  because we know that the DB has no real data, updating DB without losing the data is possible but need harder processes, so the easiest way to update the DB in developments stage is to rebuild it, but for sure this will not happen in the production stage

**Comment by theharrisonmoore** [comment]
Okay, thanks for the update.

<https://earwig.kickoffpages.com/>
