### ISSUE TITLE
Change button labels

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#284]
@thejoefriel An early piece of feedback from user testing has been that the buttons for adding comments are causing users confusion. Currently, the buttons say 'Return' and 'Submit' (see image).

![Adding comments buttons](https://user-images.githubusercontent.com/45825100/58427855-b74a6080-8098-11e9-8555-a1acf3b9b425.jpg)

The buttons need to be changed to say 'Cancel' and 'Save.' And, in fact, the Cancel button does the same thing as the X in the corner. Perhaps we should remove the Cancel button altogether as it's not needed?

**Comment by RamyAlshurafa** [comment]
done!
