### ISSUE TITLE
Adding blurred backgrounds on profiles (Level 1 access only)

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#287]
@thejoefriel As promised, here are the blurred backgrounds for when users cannot see all data (Level 1). Let me know if you need them as JPEG or something else.

![Blurred background for desktop](https://user-images.githubusercontent.com/45825100/58471647-452b5780-813c-11e9-921e-4aead161659a.png)
![Blurred background for mobile](https://user-images.githubusercontent.com/45825100/58471648-452b5780-813c-11e9-8668-ae6d549f1c4e.png)

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore - is this one still relevant?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Yes it is. This is from sprint 1. I
sent you the blurred effects as images as that's what you asked for.

<https://earwig.kickoffpages.com/>
