### ISSUE TITLE
Changing copy in the just verified pop-up

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#288]
@thejoefriel This can be added to Sprint #2.

When a user uploads a verification photo they see a pop-up which currently says 'Thanks.'

This pop-up needs to say: 'Thanks. We're checking your photo. This might take a few hours. You can still give reviews while we're checking your photo and they'll be shown on earwig once we've checked.'

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore - is this still relevant?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Yes, but it's not vital so leave it
and we'll visit it later.

<https://earwig.kickoffpages.com/>

**Comment by theharrisonmoore** [comment]
@thejoefriel This may come in sprint 3 so I'm closing the issue.
