### ISSUE TITLE
I cannot give a review

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#289]
@thejoefriel @dupreesi 

I'm going to use the new bug-reporting process Joe gave me.

Description
When I try to give a review, it navigates me back to the Search page.

Video
https://www.loom.com/share/7ee7ab1fbd8b43e99295b6b2421e7fd6

Device, Version & browser
2017 MacBook Pro 13", 10.14.5, Chrome

**Comment by dupreesi** [comment]
@theharrisonmoore can you please refresh your browser, log out and log in again and re-try?
it might have been that the database hasn't been rebuild at the point of time

**Comment by theharrisonmoore** [comment]
@Simon Dupree <simon@yallacooperative.com> thanks, it works now.

<https://earwig.kickoffpages.com/>
