### ISSUE TITLE
Replace the earwig logo

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#291]
@thejoefriel 

Here's the new earwig logo (better quality and complete with BETA tag)

https://drive.google.com/file/d/1YjSeUCMP3c7kTlqrkxtBPO_Z1zGUqQsE/view?usp=sharing

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore - on what pages do you want this? I put it on the search bar but it starts making the earwig logo itself a bit small - happy to play with size though if it's necessary to have everywhere.

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> The beta logo needs to be everywhere,
except on emails that go out to users.

<https://earwig.kickoffpages.com/>
