### ISSUE TITLE
Amenities that are not present (ie public transport, parking, storage, etc.) need to be striked-through

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#294]
Hi @theharrisonmoore - you've said that this was in the original wireframes but I've looked at them again and they are not striked through? They are just red? Screenshot attached: http://www.clipular.com/posts/5645224010055680?k=LCclENaXU6F6f4fjiPXde1fhkso

Am I looking at the wrong bit?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> The original spec I gave to you from
Sketch did include strikethroughs. See attached. I think you missed them
out when you created the designs in Figma.

<https://earwig.kickoffpages.com/>

**Comment by theharrisonmoore** [comment]
Ah annoying. The import must have lost them for some reason. OK will fix
that today.

**Comment by theharrisonmoore** [comment]
No problem, thanks Joe.

PS I'm gonna get back to you about your longer email shortly…

<https://earwig.kickoffpages.com/>
