### ISSUE TITLE
No Worksites are visible

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#296]
@dupreesi Hi Simon, I'm on the website now, and there are no worksites listed, neither in the Admin view.

2017 MacBook Pro, 10.14.5, Chrome

**Comment by dupreesi** [comment]
@theharrisonmoore sorry that was my mistake -> will restore it asap and let you know. sorry again

**Comment by theharrisonmoore** [comment]
No problem

<https://earwig.kickoffpages.com/>

**Comment by dupreesi** [comment]
@theharrisonmoore I've rebuilt the database and we've addressed the latest bugs u've raised.
