### ISSUE TITLE
Stars are filled-in irrespective of number of reviews

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#307]
@thejoefriel @dupreesi Here you can see that every profile has 5 stars, even the ones with 0 reviews and even where I have reviewed them but given them 1 star or 3 stars.

![thumbnail (1)](https://user-images.githubusercontent.com/45825100/58746980-913c0c00-845c-11e9-9f41-b1b076d1adf1.jpeg)

**Comment by amusameh** [comment]
This seems to be fixed and working as expected.
closing it.
