### ISSUE TITLE
Could we add loading animations to all buttons, like we have for reviews?

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#310]
@thejoefriel @dupreesi There are still some buttons throughout the site (eg when signing up and getting verified) that don't pop or animate when clicked. While they do work, there's something irritating about not getting a response from buttons when clicked. Construction workers won't have much patience so we should make it as responsive as possible.

Appreciate this is out-of-scope for Sprint #1.

**Comment by thejoefriel** [comment]
This is picked up in #365
