### ISSUE TITLE
Set up third party apps

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#327]
- [x] Zendesk
- [x] LogRocket
- [x] MixPanel
- [x] Google Analytics
- [x] Mailchimp
- [x] Sentry
- [x] FireBase

**Comment by amusameh** [comment]
Mailchimp is done!

**Comment by amusameh** [comment]
Baggsy sentry next :joy:

**Comment by thejoefriel** [comment]
hey @theharrisonmoore re zendesk do you have a certain channel set up for us to integrate/

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Here's a video showing how to find
the widget setup:
https://drive.google.com/open?id=1-R2BecQ_7VSgYnE6irAZXtwFo5zNbkU6
-

Best,
Harrison Moore
