### ISSUE TITLE
I can reset my password through a link emailed to me by clicking 'Forgot password?'

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#328]

**Comment by RamyAlshurafa** [comment]
Hey @theharrisonmoore 
can you create a wireframe for this feature (reset password), please?

**Comment by RamyAlshurafa** [comment]
also what the email should we use to send this type of emails?

**Comment by theharrisonmoore** [comment]
@ramy@yallacooperative.com <ramy@yallacooperative.com> Please use
hello@earwig.work

I will send you a wireframe shortly. Just to check, do you mean a wireframe
for the email users will receive, or something else?
<https://earwig.kickoffpages.com/>

**Comment by RamyAlshurafa** [comment]
yeah I mean both of the email design and the wireframes for reset page since the new wireframes don't include this, or I didn't notice them?

**Comment by theharrisonmoore** [comment]
@ramy@yallacooperative.com <ramy@yallacooperative.com> You're right. I
forgot to include. I'll do these this week. Would you be able to wait a few
days for this particular design?
<https://earwig.kickoffpages.com/>

**Comment by RamyAlshurafa** [comment]
yeah, that's fine for me, thanks

**Comment by theharrisonmoore** [comment]
@RamyAlshurafa You will find the wireframes for the password reset in the new wireframes Joe uploaded to Figma today. Here is the text for the email:
[Password reset email.pdf](https://github.com/yalla-coop/earwig/files/3303369/Password.reset.email.pdf)
