### ISSUE TITLE
Instead of having to type numbers into boxes on money-related questions, I can drag a slider

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#334]
This will range from zero > £50+ (increasing in increments of £1).

**Comment by theharrisonmoore** [comment]
@thejoefriel I have been told by workers that occasionally (it never happened to me) they are paid £X.50. We therefore need to ensure the sliders increase by increments of 50p.

Best to do this for all sliders, ie hourly rates and car parking, etc.

I am sorry I didn't foresee this earlier and I hope it's not too much extra work?
