### ISSUE TITLE
All new users' emails are added to a mailchimp list 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#339]
Relates to mailchimp set up #327

**Comment by amusameh** [comment]
Hi @theharrisonmoore 
In the previous sign up we send the user email if he want to join earwig mail-list I think it would be easier and more accessible to add a checkbox in the signup form and user can check it if they want to join mail list .

In mail-chimp free plan I can create **only one mail-list**. which will contain all the emails for the signed up user weather they agreed or not to receive extra emails with earwig news, deals and offers.

I want to check if you are happy with this

**Comment by theharrisonmoore** [comment]
Hi, I need to check something with the lawyers. Could we put this issue on
hold for a couple of days?

<https://earwig.kickoffpages.com/>

**Comment by amusameh** [comment]
@theharrisonmoore  You sure. please let me know when you check that. thanks

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Hi Abdulsamad, the lawyers have
confirmed that the opt-in clause is in fact already included in the earwig
Terms of Use. This means we do not need to ask users to opt-in with a tick
box or send them an email. Sorry about the confusion there; it was
my mistake.

Going forward, we can add all users to a single audience (list) in
MailChimp.

<https://earwig.kickoffpages.com/>
