### ISSUE TITLE
When giving an agency review and reading the question 'What hourly rate were you paid?' I can click the words 'Why are we asking you this?' to see an explanation in a popup

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#358]

**Comment by dupreesi** [comment]
@theharrisonmoore @thejoefriel what should the wording for the explanation be like?

**Comment by theharrisonmoore** [comment]
@Simon Dupree <simon@yallacooperative.com> The wording is contained in the
wireframe. See here:

[image: Screenshot 2019-06-24 at 13.49.48.png]

<https://earwig.kickoffpages.com/>

**Comment by dupreesi** [comment]
thanks @theharrisonmoore
