### ISSUE TITLE
I can change my earwig ID

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#361]

**Comment by thejoefriel** [comment]
@theharrisonmoore - for this feature, can they change it to anything they want? Do we want any limitations as to the length, letters numbers etc?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> I don't have any limitations.
Although, maybe we should limit the number of characters. Do you have any
ideas on how many is a reasonable number?
-

Best,
Harrison Moore

**Comment by thejoefriel** [comment]
thanks @theharrisonmoore 

I'd say no longer than 15 characters (this is in line with Twitter etc) and no spaces if that works for you

**Comment by theharrisonmoore** [comment]
Sounds good mate! Less is more

-

Best,
Harrison Moore

**Comment by theharrisonmoore** [comment]
@thejoefriel Just thought of something that could be important. Usernames should be case sensitive, eg SuperSparky1999 instead of supersparky1999

Is this possible?
