### ISSUE TITLE
I can export review data as a raw CSV

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#366]

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore - what data do you want to export as a CSV, would it be a row for each review with then the columns being the questions? And then also including the reviewers details and the organisation details being reviewed?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Could we talk about this on the phone
or even in person? It's such a crucial part that it needs some proper
thought and I've been looking forward to speaking to you about this.

-

Best,
Harrison Moore

**Comment by theharrisonmoore** [comment]
@thejoefriel Here is an example spreadsheet showing the data we need to be able to export as CSV: https://docs.google.com/spreadsheets/d/1e7SLTAFqJJ62sPQRw0GY2cufUVmp_gZBQVZi5BMYuPs/edit?usp=sharing

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore - I think it might be better to have the questions in the column headers? Like this: https://docs.google.com/spreadsheets/d/1SdwjEAvjywj5VKVCSw9ftrTqw1ezll1eWPAbTdh50D0/edit?usp=sharing

That way you will be able to easily sort by question for example to see what the overall answers to that question is. 

What do you think?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Yep, that make so much sense! Thanks

-

Best,
Harrison Moore

**Comment by thejoefriel** [comment]
Great!
