### ISSUE TITLE
I can see the name of the main contractor on Worksite profiles

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#383]

**Comment by RamyAlshurafa** [comment]
Hi @theharrisonmoore 
I have a suggestion about displaying the contractor on the worksite profile,
what if we displayed the latest contractor from the reviews and make a small list with a dropdown list to view the full list of contractors?

**Comment by theharrisonmoore** [comment]
@ramy@yallacooperative.com <ramy@yallacooperative.com> Yes, I think that
could work, providing the box isn't too big and attention-grabbing.

<https://earwig.kickoffpages.com/>
