### ISSUE TITLE
Each time a review is given about an entity, an email is sent to every other worker who is currently working with this entity notifying them that a review was given. The email contains a link inviting them to give a review also

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#384]

**Comment by thejoefriel** [comment]
@theharrisonmoore - can you provide the email title, which email address it should be sent from and the wording for the message please?

Also, I'm assuming that we'd need to check so that workers who already have given a review won't get the email?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Let's push this back to Sprint 3.
I've updated the user story so you don't have to.

<https://earwig.kickoffpages.com/>

**Comment by thejoefriel** [comment]
Ok sure thing :)

**Comment by theharrisonmoore** [comment]
@thejoefriel This may come on sprint 3 so I'm closing this issue.
