### ISSUE TITLE
User Journeys

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#4]
Hi @theharrisonmoore - do you have user journey(s) written out as well? Would be useful if we could store these

**Comment by theharrisonmoore** [comment]
@thejoefriel I'm not sure what you mean. You have the User Stories in the Google Sheet, right? I don't have them in any other format.

**Comment by theharrisonmoore** [comment]
Oh, you mean user _journeys_? There are two key user journeys in this attached MVP Spec.
[earwig MVP Spec.pdf](https://github.com/yalla-coop/earwig/files/3035372/earwig.MVP.Spec.pdf)

**Comment by theharrisonmoore** [comment]
Sorry… I closed the issue by accident.

**Comment by thejoefriel** [comment]
No worries. Yes, that's amazing thanks @theharrisonmoore
