### ISSUE TITLE
I keep receiving this email every day

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#400]
@thejoefriel @RamyAlshurafa Hi guys, I keep receiving this email every day:

<img width="1346" alt="Screenshot 2019-06-22 at 10 18 52" src="https://user-images.githubusercontent.com/45825100/59961987-3a63a880-94d7-11e9-80a5-2a43e05cf315.png">

**Comment by RamyAlshurafa** [comment]
@theharrisonmoore 
This is not related to the app
from the email address `no-reply@github.com` it seems like you tried to send an email to this address which is not receiving emails
