### ISSUE TITLE
5 point PPE icon

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#408]
Hi @theharrisonmoore is there an icon you want put next to this or do you want this to be a Yes No question?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Yes, there is an icon. See image
attached.

[image: Screenshot 2019-06-25 at 17.30.32.png]

Here's the icon URL: https://www.flaticon.com/free-icon/gas-mask_1878550
<https://earwig.kickoffpages.com/>

**Comment by thejoefriel** [comment]
Great that's been added :)
