### ISSUE TITLE
Add 'From' and 'To' tags to date inputs

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#409]
@thejoefriel 
This wasn't agreed as part of Sprint 2 but it's really important because most workers are misunderstanding why there are two boxes. Would you be able to fit this into Sprint 2?

As I can't edit in Figma, here's a screenshot of what it needs to look like:

<img width="1193" alt="Screenshot 2019-06-26 at 10 13 20" src="https://user-images.githubusercontent.com/45825100/60167668-73fc2280-97fb-11e9-8c43-52ccc8929941.png">

**Comment by RamyAlshurafa** [comment]
closing, since it's done
