### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#415]
Hey @theharrisonmoore 

You ok to send over the new icons from the wireframes please? Same as before with a link to where we can get them on flaticon would be amazing!

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Sure, in fact, I believe the icons
you need are already pasted as links in the User Stories Sheet. See row 54:
https://docs.google.com/spreadsheets/d/1FYGTogNHkA85wl2gR2NrLbba2Nt5onO6DhI_OoIDSJw/edit#gid=1216173505

<https://earwig.kickoffpages.com/>
