### ISSUE TITLE
Issues with the main icons still 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#431]
Hey @theharrisonmoore - we're still having lots of issues with being able to manipulate the 4 main icons (agency, company, payroll, worksite). This is mainly due to them being images converted to SVG. We really need working versions to ensure we can properly change the colour on them etc. 

Are you able to send across please?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Certainly, I can do that today. What
format do you need them to be exactly? I took PNG icons from a library and
then made my own edits to them in Photoshop and exported them as PNG. What
should I do instead?
-

Best,
Harrison Moore

**Comment by thejoefriel** [comment]
Ideally these would be SVGs. 

However, if this ends up not being possible then I guess we need a black and white version of each pngs and then also in their organization colour too. 

As I say though SVGs are the preferred format please!

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> I'll send them as I find them. Here
are icons for the Agency icon attached.
-

Best,
Harrison Moore

**Comment by theharrisonmoore** [comment]
Payroll icon attached
-

Best,
Harrison Moore

**Comment by theharrisonmoore** [comment]
Worksite icon attached
-

Best,
Harrison Moore

**Comment by theharrisonmoore** [comment]
Company icon attached
-

Best,
Harrison Moore

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore sorry nothing seems to be attached!
