### ISSUE TITLE
This button does not animate to show progress

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#441]
@thejoefriel 

![This button does not animate to show progress](https://user-images.githubusercontent.com/45825100/61033592-b86eed00-a3bb-11e9-9e27-049d9126b841.jpeg)

iPhone SE, Safari

**Comment by amusameh** [comment]
Hi @theharrisonmoore  This should be an instant redirect so I think no need for for loading icon here.
Please let me know if you have something else in your mind. thanks

**Comment by theharrisonmoore** [comment]
Hi @amusameh I see your point. The trouble is, the page did not load quickly and so I was left wondering if I'd clicked the button or not, which is frustrating as a user. Would it be extra work to add the animation you created to all buttons on the site?

**Comment by amusameh** [comment]
@theharrisonmoore Thanks for your quick response.
Yeah, I understand. I made some changes and this button will redirect instantly from now on. I just checked it in Heroku link and it seems to work as expected. I will look into adding the spinner(No extra work but this should's happen and should redirect instantly) if that didn't work for you.
We will warp up a few final issues and have the link ready for you to check.

**Comment by theharrisonmoore** [comment]
Thanks Abdal.

Overall, I'm happy for buttons to be static providing there's no chance of
there being a delay after being clicked. if there is any chance of a page
taking a few seconds to load, I would prefer it if the button had the
animation.
-

Best,
Harrison Moore
