### ISSUE TITLE
This question should have been removed from the Payroll review and profile

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#461]
@thejoefriel 

![This question should have been removed from the Payroll review and profile](https://user-images.githubusercontent.com/45825100/61039887-82376a80-a3c7-11e9-9acd-2d62b151302c.jpeg)

**Comment by amusameh** [comment]
Hi @theharrisonmoore 
Just to be sure do you want me to delete the question 5 from payroll (screen shot) and hide the chart from the profile page as I don't recall that you asked us to delete it before.

![Screenshot from 2019-07-14 12-43-09](https://user-images.githubusercontent.com/28042978/61181913-09d5e100-a635-11e9-99cf-5baa21ecda43.png)

**Comment by theharrisonmoore** [comment]
@amusameh I have made a mistake with this bug. Please don't delete it. Sorry about the confusion. Thank you for double-checking with me.

**Comment by amusameh** [comment]
@theharrisonmoore  No worries.
