### ISSUE TITLE
Lots of spinning wheel when using the app

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#463]
@thejoefriel 

https://drive.google.com/open?id=1GAHVKxKmta30cznbqQZiHn97jSlbUAJQ

iPhone SE, Safari

**Comment by theharrisonmoore** [comment]
@amusameh Spinning wheel when trying to change earwig ID.

https://drive.google.com/open?id=1iR9C-FDC7v-KVuSYYbZqngA3qjcwBzun

**Comment by thejoefriel** [comment]
Have carried out this test on iPhone SE and it updates fine now so closing this issue
