### ISSUE TITLE
When giving a quick review, I can answer a series of questions by clicking 'Yes,' 'No,' and other buttons (Level 3)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#47]
Relates to #40 

- [ ] Radio button inputs
- [ ] Checkbox inputs

**Comment by thejoefriel** [comment]
@theharrisonmoore - quick question on this. Can the user skip questions or do they have to answer every question?

**Comment by theharrisonmoore** [comment]
I had always planned to allow users to skip any questions. But, what do you
think? Allowing skipping would feel less controlling for users. But, this
might lead to inconsistencies in data. From a dev point of view, is
inconsistent data more or less of a headache?
<https://signup.earwig.work/>

**Comment by thejoefriel** [comment]
@theharrisonmoore - it should be fine to allow all the questions to be optional and is more user-friendly. Will let you know if we hit major issues
