### ISSUE TITLE
Terms and policies should always open in new window

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#480]
@thejoefriel 

https://drive.google.com/open?id=1rKVQnv5qCg-AqWjuNAOF6aUNMqBJbowN

**Comment by thejoefriel** [comment]
@theharrisonmoore - we've fixed this now and will be merging into the develop branch shortly 👍 😄 . Did you add this clarification to the user story when created as an issue? If not, this is something that would be great to please add to future issues just so we're absolutely clear what is expected.

**Comment by theharrisonmoore** [comment]
Great, okay, I'll make sure I do that now!
-

Best,
Harrison Moore
