### ISSUE TITLE
Audio player

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#489]
Hi @theharrisonmoore - we have fixed the audio player so that it now plays fine on all browsers and any version of Safari >= 11.

Unfortunately web audio player compatibility can't go back prior to that version. Hope that's ok. Let me know if any major issues and you wish to discuss.

**Comment by RamyAlshurafa** [comment]
just tested and worked for safari 10.14

**Comment by theharrisonmoore** [comment]
Hi guys, sounds like great news! I'm away at a conference for two days but
I'm planning to work on testing on Wednesday, so I'll be able to jump on
this then. Hope that's okay?
-

Best,
Harrison Moore
