### ISSUE TITLE
When trying to add a new entity, I'm taken to the homepage by mistake

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#497]
@thejoefriel 
When trying to add a new entity, I'm taken to the homepage by mistake.

I know we haven't accounted for being able to add new entities at this stage, but it's clear it needs to be possible otherwise this flow simply won't make sense for a bunch of users. Will this need to be added to Sprint 3 or do you think you can fit this into Sprint 2?

Samsung Galaxy S9, Chrome

https://drive.google.com/open?id=1A6HfoldFlaIPYcrVHJlQorpG3D9sXe3-

**Comment by thejoefriel** [comment]
This has been added and done in this sprint 2
