### ISSUE TITLE
Page loads zoomed in and can't see title

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#500]
@thejoefriel 

Page loads zoomed in and can't see title

Iphone SE, Safari

![Page loads zoomed in and can't see title](https://user-images.githubusercontent.com/45825100/62193980-d30c0480-b370-11e9-9a5b-06aa62c47513.jpg)

**Comment by thejoefriel** [comment]
Have checked this on iPhone and is fixed.
