### ISSUE TITLE
Once verified, Page loads zoomed in and can't see title

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#501]
@thejoefriel 

Once verified, Page loads zoomed in and can't see title

Iphone SE, Safari

![Page loads zoomed in and can't see title](https://user-images.githubusercontent.com/45825100/62194246-66ddd080-b371-11e9-9f30-23789397b3eb.jpeg)

**Comment by thejoefriel** [comment]
Have checked on iPhone and this is fixed
