### ISSUE TITLE
Once verified, I am unable to contact entity by call, email or website

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#502]
@thejoefriel 

Once verified, I am unable to contact entity by call, email or website

Iphone SE, Safari

https://drive.google.com/open?id=1ob24sQ7XbhSZ8VLhTuZnxc-_K7Tfr3sa

**Comment by thejoefriel** [comment]
Tested this across multiple devices and is working fine so closing this issue for now
