### ISSUE TITLE
Spinning wheel of death when trying to create an account

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#504]
@thejoefriel 

Spinning wheel of death when trying to create an account.

iPhone SE, Chrome

https://drive.google.com/open?id=1aD866TbBL2FZ1hY7_j4IdK6hL3-W8U9C

**Comment by theharrisonmoore** [comment]
Samsung Galaxy S9, Samsung Internet

(Eventually worked after 30 seconds + waiting)

https://drive.google.com/open?id=1K-GsYzxFwcxDQ4ILE6TvFCEGM0MrrsCk

**Comment by thejoefriel** [comment]
We can't reenact this bug so going to close but speed is something we should definitely look to refactor in sprint 3
