### ISSUE TITLE
When reviewing an agency, I can add the name of the associated Payroll by selecting it from a drop down list (I can add the Payroll name if it is not listed) (Level 3)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#51]
Relates to #40 

PLEASE NOTE: This does not add any data or then make it count as a review of that Payroll. 

- [ ] Dropdown input
- [ ] Option to add the payroll if not listed

**Comment by theharrisonmoore** [comment]
@thejoefriel 
Adding a Payroll will not add them to the database list, it will show them on the Agency Profile data.

**Comment by thejoefriel** [comment]
Cool, yes that's what I thought. Thanks for confirming :)
