### ISSUE TITLE
I cannot add a new trade

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#512]
@thejoefriel 

I cannot add a new trade

Once I've typed in a new trade - I click done and then the trade name disappears so I am unable to "save new trade"

Iphone SE, Safari

https://drive.google.com/open?id=1o709I_5Ir2bTG4oaGxR-BE-3EoJ36Ru_

**Comment by RamyAlshurafa** [comment]
@theharrisonmoore 
this video link is broken, could you make another one, please?

**Comment by theharrisonmoore** [comment]
@RamyAlshurafa I'm sorry, I cannot find the original video. And I did not save it on my device.

This issue is similar to others when trying to add a new trade. I think the 'add item' button needs to be at the top of the list instead of the bottom.
