### ISSUE TITLE
Menu is not useable because it's too squashed.

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#514]
@thejoefriel 

Menu is not useable because it's too squashed.

iPhone SE, Chrome

![Menu is not useable because it's too squashed](https://user-images.githubusercontent.com/45825100/62197010-fafe6680-b376-11e9-86d3-09e9a91b8fea.jpeg)

**Comment by thejoefriel** [comment]
This was fixed on another issue
