### ISSUE TITLE
When creating a new entity, it tells me I've already added it when I haven't. It does show up in Admin however

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#518]
@thejoefriel 

When creating a new entity, it tells me I've already added it when I haven't. It does show up in Admin however. (See both videos)

Iphone SE, Safari

https://drive.google.com/file/d/15TV90twhPrlbsG_WGg71VwZViIz1elzv/view?usp=sharing

https://drive.google.com/open?id=1YmI87S8veW_EePb3paVLECogabp4yNg7

**Comment by amusameh** [comment]
same as #519
