### ISSUE TITLE
I cannot add new entity profiles because it says I've already created them. They still show up in Admin, though.

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#519]
@thejoefriel 

I cannot add new entity profiles because it says I've already created them. They still show up in Admin, though.

iPhone SE, Chrome

https://drive.google.com/open?id=19tqFeD-cHru7sK60UKWcNelAtcHP6eS-

**Comment by theharrisonmoore** [comment]
All devices

Asus Laptop, Windows 10, Microsoft Edge

**Comment by amusameh** [comment]
duplicated
