### ISSUE TITLE
Entity websites don't load.

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#521]
@thejoefriel 

Entity websites don't load.

iPhone SE, Chrome

https://drive.google.com/open?id=1tC21ZtOwH5izO-rIY0GQsaQcEC-sENI6

**Comment by thejoefriel** [comment]
We can't replicate this on my own iphone SE Chrome using either mobile network or wifi, and I tested with that exact same company. Do you mind retrying please @theharrisonmoore ?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joseph.s.friel@gmail.com> This is now working
-

Best,
Harrison Moore
