### ISSUE TITLE
When reviewing a payroll, I can add the name of the associated Agency by selecting it from a drop down list (I can add the Agency name if it is not listed) (Level 3)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#53]
Relates to #40 

PLEASE NOTE: adding an agency will not add them to the database list, it will show them on the Payroll Profile data.

- [ ] drop down input
- [ ] Add agency if not included

**Comment by theharrisonmoore** [comment]
"PLEASE NOTE: Adding an agency does not add them to the database list, it will just show them in this review." > This is not quite correct. Rather, adding an agency will not add them to the database list, it will show them on the Payroll Profile data.

**Comment by thejoefriel** [comment]
Sorry yes that's what I meant - have edited to make clearer
