### ISSUE TITLE
earwig ID, trade, and points are missing.

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#538]
earwig ID, trade, and points are missing.

iPhone SE, Chrome

![earwig ID, trade, and points are missing](https://user-images.githubusercontent.com/45825100/62207079-22f7c500-b38b-11e9-8a4a-a9d2baab843c.jpeg)

**Comment by thejoefriel** [comment]
Tested on iphone SE chrome and all working now
