### ISSUE TITLE
On my profile, in the list of reviews I've given, when I click an entity name to navigate to their profile I'm taken to a page with an error message.

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#540]
On my profile, in the list of reviews I've given, when I click an entity name to navigate to their profile I'm taken to a page with an error message.

iPhone SE, Chrome

https://drive.google.com/open?id=11L-kyyEjPZrHA5NYSyqGC8Y9yk7jMbhM

**Comment by thejoefriel** [comment]
This is now working on iphone SE chrome so I'm now closing
