### ISSUE TITLE
After making a review on a worksite, I can no longer see the review or the worksite profile

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#541]
After making a review on a worksite, I can no longer see the review or the worksite profile

Iphone SE, Safari

https://drive.google.com/file/d/1jxuh5cBaV_7fnoC_xG7wj3OVAuJcSGjO/view?usp=sharing

**Comment by dupreesi** [comment]
@amusameh i think this issue might be sorted with the refactoring you've done..

**Comment by theharrisonmoore** [comment]
@Simon Dupree <simon@yallacooperative.com> Sorted!
-

Best,
Harrison Moore
