### ISSUE TITLE
When trying to give a review to then edit, various bugs….

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#543]
When trying to give a review to then edit, various bugs…. firstly the Most recent reviews list didn't show. I then tried to search for a company but no results were given. After refreshing the page I could find the company I was looking for. Having given a review, I then went to edit the review but was shown an error page.

iPhone SE, Chrome

https://drive.google.com/open?id=1sP22tqksFM72HcAeShe9CVHFQI_eBhwU

**Comment by thejoefriel** [comment]
These have all been fixed in other issues now 👍
