### ISSUE TITLE
I never saw the Welcome video having gotten verified

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#550]
I never saw the Welcome video having gotten verified.

iPhone SE, Chome

**Comment by thejoefriel** [comment]
@theharrisonmoore - I think this user flow needs some thinking. 

When they first sign up, they are then logged in. This means that when you verify them there is no easy way to suddenly show them the welcome video and there's a risk it would lead to a really bad user experience (for example what if they're currently filling in a review at the time).

You could potentially do it if they log out and log back in, but that again doesn't seem like a great user experience. 

Also, when they first sign up, even though they aren't fully verified, you are at that allowing them to do everything (they can create reviews, see profiles etc), and then it's simply that their reviews become public once they're verified. So I would argue, it makes much more sense and is a better user experience to see the intro video when I've first signed up, not when you've then verified me. It is at the stage of signing up that am excited to learn about earwig and what I can do on the platform, not at a later stage (verification) that now kind of happens behind the scenes. 

So what I'd suggest is when a user signs up, if they say they're a worker, then they are shown the intro video. 

What do you think?

**Comment by theharrisonmoore** [comment]
Hi Joe, I've given it some thought. I think you're right. Let's keep it
simple. Go with your suggestion.
-

Best,
Harrison Moore

**Comment by thejoefriel** [comment]
Thanks very much Harrison. Let's make sure to test this as well so we can iterate if they feel there needs to be more fanfare about them being verified.
