### ISSUE TITLE
I can't edit my reviews

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#558]
I can't edit my reviews

Macbook pro, Safari

https://drive.google.com/open?id=1hPJIWW710vQ6q3WZ5Ps1ltZ-Ey2Yrlbr

**Comment by theharrisonmoore** [comment]
Samsung Galaxy S9, Samsung Internet

**Comment by theharrisonmoore** [comment]
Asus Laptop, Windows 10, Microsoft Edge

**Comment by theharrisonmoore** [comment]
Samsung Galaxy S9, Chrome

**Comment by amusameh** [comment]
same issue as #566
