### ISSUE TITLE
I can make 2 reviews on the same entity in the same month when I change my trade

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#565]
I can make 2 reviews on the same entity in the same month when I change my trade

When I signed up, I made my trade Gate Keeper - I then did a review on Payplus, and after completing the review I could not review the company again. I then changed my trade to General Labourer and was able to complete a second review on Payplus, despite doing the earlier one on the same day.

Macbook Pro, Chrome

<img width="1440" alt="I can make 2 reviews on the same entity in the same month when I change my trade" src="https://user-images.githubusercontent.com/45825100/62227917-ab3e9000-b3b4-11e9-852a-2c0ed29d30fe.png">

**Comment by RamyAlshurafa** [comment]
this is solved in the last fix bugs PR
