### ISSUE TITLE
I can make a voice recording longer than 30 seconds

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#577]
When making a review, I can make a voice recording longer than 30 seconds

Samsung Galaxy S9, Samsung Internet

![I can make a voice recording longer than 30 seconds](https://user-images.githubusercontent.com/45825100/62286137-0b821000-b44f-11e9-974e-a29071412aa7.JPG)

**Comment by thejoefriel** [comment]
@theharrisonmoore - do you think this is necessarily a bug we should fix at this stage? They aren't able to upload files so there's minimal chance of issues with huge files being uploaded to the server, and perhaps it'd be best to see in user testing whether they need it to be 30 seconds or would like it to be longer? What do you think?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> I guess you make a good point. My
only concern would be if they somehow left their phone recording and it
then uploaded an hour-long recording to the server. Could this happen? If
not, then I agree we can leave this to see how it plays out.
-

Best,
Harrison Moore

**Comment by thejoefriel** [comment]
Cool. Will close this for now and we can re-approach after further testing.
