### ISSUE TITLE
After completing a review, the email sharing icon has lost the outline of the envelope

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#599]
After completing a review, the email sharing icon has lost the outline of the envelope

When hovering over the icon, I can see it faintly

Asus Laptop, Windows 10, Microsoft Edge

https://drive.google.com/open?id=1cIg6uYEgS7Uzlsw50krJCqFx5h9xl_Ob

**Comment by thejoefriel** [comment]
![Screenshot 2019-08-07 at 08 55 51](https://user-images.githubusercontent.com/19708921/62605052-36f27800-b8f1-11e9-9e18-281eca0903b3.png)

This has been resolved. Screenshot shows platform on Edge
