### ISSUE TITLE
When giving helpfulness points, a black bar begins to cover the "this is helpful" button, until after giving 10 points, the whole label is black

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#600]
When giving helpfulness points, a black bar begins to cover the "this is helpful" button, until after giving 10 points, the whole label is black

Asus Laptop, Windows 10, Microsoft Edge

https://drive.google.com/open?id=17h3_sresHSRqUEgU1j-YuHCnfELprl_7

**Comment by RamyAlshurafa** [comment]
Hey @theharrisonmoore 
could you test this again, please?

**Comment by theharrisonmoore** [comment]
Hi Ramy, as I do not have a PC (only Mac), I cannot test this again until I
borrow a PC from a friend. I will try to do this as soon as possible.
-

Best,
Harrison Moore

**Comment by theharrisonmoore** [comment]
@RamyAlshurafa 

On second thoughts, I actually quite like the fact that the button fills up as users click it. It makes it clearer. I'm going to close this issue.
