### ISSUE TITLE
When sending a referral link from Windows 10, Microsoft Edge the link in the email is not hyperlinked

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#603]
When sending a referral link from Windows 10 Microsoft Edge the link in the email is not hyperlinked (unlike sending from other browsers)

Asus Laptop, Windows 10, Microsoft Edge

<img width="1036" alt="When sending a referral link from Windows 10 Microsoft Edge the link in the email is not hyperlinked" src="https://user-images.githubusercontent.com/45825100/62304230-7e9e7d00-b475-11e9-8305-6431b59504c2.png">

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore - the browser doesn't control whether this link is hyperlinked. I think this is more an issue with Mail in Windows 10 which we have no control over. Sorry about that. Going to close this for now.
