### ISSUE TITLE
I can navigate to Help shape earwig section, which is a static page

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#61]
This is the help screen on Figma

**Comment by thejoefriel** [comment]
@theharrisonmoore I realised that we didn't have a user story for the fact that when a user submits a comment on these help pages that they get sent to you via email. 

I've added this in. However, since email functionality for you is part of the second sprint, I'd suggest for the help page that rather than the comment box we first simply include your email address if that's ok? We'll then integrate the comment box when we build the relevant functionality in sprint 2.

**Comment by theharrisonmoore** [comment]
Sure, that's okay.

NB: We're yet to set up the email address. I have the domain (earwig.work)
sat on GoDaddy, which you'll be using for the site. I assume an email
address will then be set up in tandem with this?

<https://signup.earwig.work/>
