### ISSUE TITLE
I can navigate to Explainer videos section, which is a static page

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#62]
This is the FAQ screen - include video embeds where relevant

**Comment by thejoefriel** [comment]
@theharrisonmoore - am i right that the explainer videos section is the same as the FAQ section? That's what we have on the Figma screens.

**Comment by theharrisonmoore** [comment]
There is just one page called 'FAQ & explainer videos'
<https://signup.earwig.work/>
