### ISSUE TITLE
Strange info appears on screen when giving review. Also, voice recording element is duplicated with buttons that shouldn't be there

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#634]
@thejoefriel 

Strange info appears on the screen when giving a review.

Also, voice recording element is duplicated with buttons that shouldn't be there.

iPhone SE, Chrome

https://drive.google.com/open?id=1dzRs-57In5q9PRQMnVT12UKL57n_pSva

**Comment by amusameh** [comment]
Hi @theharrisonmoore 
I'm showing these info for my work to debug the voice stuff on heroku.
I'll be updating this soon and deleting these info.
Thanks

**Comment by theharrisonmoore** [comment]
@amusameh Okay, no problem, thanks for getting back to me so quickly!

**Comment by amusameh** [comment]
@theharrisonmoore  thanks.
I'll let you know when everything is ready for you to test.

**Comment by theharrisonmoore** [comment]
Great, thank you.
-

Best,
Harrison Moore
