### ISSUE TITLE
When trying to edit a review I've already given, I'm shown an error message

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#635]
@thejoefriel 

When trying to edit a review I've already given, I'm shown an error message.

iPhone SE, Chrome

https://drive.google.com/open?id=1sMFbPSRGr1Ra5Ceq6I9mgz0MRocVPcQj

**Comment by amusameh** [comment]
Hi @theharrisonmoore 
I think you should stop the testing for a bit. I'm currently working on the develop heroku and pushing things to try it.
It would be better if you leave it until tomorrow. I'm waiting for @thejoefriel and he should confirm that to you later today or tomorrow that the link is ready for testing.

Sorry for this mix up. thank you

**Comment by theharrisonmoore** [comment]
No problem Abdal. I'll stop testing today.

-

Best,
Harrison Moore
