### ISSUE TITLE
Drop-in new explainer video to landing page, and Welcome video to welcome page 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#636]
@theharrisonmoore to supply the video link / embed code

**Comment by amusameh** [comment]
Hi @theharrisonmoore 
where I can find the links to the videos?
thanks

**Comment by theharrisonmoore** [comment]
Abdal, I will be able to give you these links at the end of this week.
Would you be able to work on the other issues until then?
-

Best,
Harrison Moore

**Comment by amusameh** [comment]
Yeah no worries.

**Comment by theharrisonmoore** [comment]
@amusameh here are the two video links:

First, here is the embed code for the new homepage video: <iframe width="560" height="315" src="https://www.youtube.com/embed/Z4F7iJeYgqE?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Second, here is the embed code for the Special message for workers video (the one they see when they get verified): <iframe width="560" height="315" src="https://www.youtube.com/embed/nV2Wbg3pMPE?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
