### ISSUE TITLE
Add additional copy to 'Invite workers to earwig' page to make it clear they'll earn 20 points

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#643]
Please refer to the wireframes on the resources issue on this.

**Comment by thejoefriel** [comment]
@theharrisonmoore - to avoid any confusion do you think you'd be able to share the actual page design on this issue please? No worries if not!

**Comment by theharrisonmoore** [comment]
@thejoefriel Sure, here:

<img width="330" alt="Screenshot 2019-08-30 at 15 07 22" src="https://user-images.githubusercontent.com/45825100/64027092-ef4dbd80-cb37-11e9-8dde-4aea1ba8e4bf.png">

Your network
is powerful!

The more workers use earwig, the more valuable it becomes for you and the worker community.

You’ll earn 20 points for every worker who gets verified using your magic link. Your points are an important measure of how helpful you’ve been to other workers. We may give awards and run competitions from time to time.
