### ISSUE TITLE
Change the messages that are sent to invite workers

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#644]
Update the messages to use this copy: https://docs.google.com/document/d/12n6ZNqiHNDub7JJ-LEepKdlQviOy9Vbwfru32LiSjPM/edit?usp=sharing

**Comment by amusameh** [comment]
Hi @theharrisonmoore 
FB policy is to leave filling the message to the users. and it's against their policy to pre-fill it.
If you still want to send the message. I'd look into some hacks into how to add it. Just want to be sure that's what you want. Please check the link below
https://developers.facebook.com/docs/apps/review/prefill/

**Comment by theharrisonmoore** [comment]
Hi Abdal, would the hack demand a lot of extra work for you?
-

Best,
Harrison Moore

**Comment by amusameh** [comment]
Hi @theharrisonmoore 
I'm afraid that's not possible. adding pre-filled text can be done for sharing content on your Facebook wall but not allowed for directly sending messages into your friends inbox.
FB API allows only sharing a link and the user can add the text they want to be sent to their friends.

I'll search more for any possible solutions though and let you know. but I can't promise anything.

**Comment by theharrisonmoore** [comment]
Abdal, nah, it's okay. Don't worry about it. Leave the message for email
and WhatsApp but leave it blank for FB.
-

Best,
Harrison Moore
