### ISSUE TITLE
Add additional copy to upload verification photo page to make it clearer why a photo is being asked for

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#645]
Please refer to the wireframes in the Resources issue

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore for simplicity, do you think you'd be ok to put the copy here please?

**Comment by theharrisonmoore** [comment]
@thejoefriel sure, here:

<img width="331" alt="Screenshot 2019-08-30 at 15 04 58" src="https://user-images.githubusercontent.com/45825100/64026903-9120da80-cb37-11e9-9f2a-895b5902987a.png">

**Verification photo**
We need to verify you’re a genuine worker so the worker community is protected from fake reviews and spam by non-workers. Please upload a photo of your face holding your trade ID like the example below. Please no glare or blur!

Don’t worry! Once we’ve verified you, we’ll delete your photo to protect your identity.

**Protecting you from blacklisting**
To protect your identity, we’ll randomly assign you an earwig Username, which is the only thing shown beside your reviews and activity.
