### ISSUE TITLE
Change copy on 'Review Thank You' pages

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#646]
Please refer to the wireframes

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore do you mind putting the copy here as well for simplicity please?

**Comment by theharrisonmoore** [comment]
@thejoefriel Sure, here:

<img width="480" alt="Screenshot 2019-08-30 at 15 03 23" src="https://user-images.githubusercontent.com/45825100/64026787-5dde4b80-cb37-11e9-8cbb-90b78b8403e5.png">

Your review will be seen by everyone in the industry and other workers who rely on reviews like yours

Don’t worry, only your earwig Username is visible beside your review

Each time you give a review, you

- Create awareness
- Improve working conditions
- Help workers feel secure
