### ISSUE TITLE
Admin: I receive an email when a new entity is added to the database

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#647]
This would include a company, worksite, payroll or agency. This would need to be done whenever an entity is added. 

@theharrisonmoore do you have specific copy (title, message you want to be sent?) If so can you please add as a comment below.

**Comment by theharrisonmoore** [comment]
@thejoefriel please use the following copy in the email to Admin:

Dear earwig Admin,

a user has just created a new entity profile.

[insert link to website]
