### ISSUE TITLE
Ensure toilet questions are in the correct order

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#650]
@theharrisonmoore so to confirm is this screen shot of the questions in the correct order? https://drive.google.com/open?id=1tVXo9UNb9TukL0EHjMEI3DQ-B_3BOlLU

And is this purely in the giving review section or the profile as well?

**Comment by theharrisonmoore** [comment]
@thejoefriel Yes, the above screenshot shows the questions in the correct order. At the moment, the female toilet question comes first so it comes across as if the next question about cleanliness is only asking about the female toilets.

This is only on the Worksite profile.
