### ISSUE TITLE
Right-justify replies from entities and make design consistent with wireframes 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#655]
To confirm, replies from 'entities' currently are simply replies from admin 
Also admin will only add replies as that 'entity' so you can assume that any admin reply should be right-aligned. 

@theharrisonmoore - this is in line with what we discussed but let us know if misunderstood! 

This is in the profile, the comments modal box and also needs to look like that when seeing previous messages when you choose to reply

**Comment by theharrisonmoore** [comment]
@thejoefriel Yes, this is correct. Please refer to this: https://drive.google.com/open?id=1pZg86FzYXhOUCyfJx_N5VnvPTd1qrFe3

**Comment by amusameh** [comment]
Hi @theharrisonmoore 
The color should be inline with the type of the entity or same as the above screen shot across all types of entities?

**Comment by theharrisonmoore** [comment]
Hi Abdal, the colour should be in line with the type of entity.
-

Best,
Harrison Moore

**Comment by amusameh** [comment]
Hi @theharrisonmoore check this and let me know what you think. thanks.

![admin reply](https://user-images.githubusercontent.com/28042978/64134989-ad996d00-cdec-11e9-9c9b-2eb1e31e7132.PNG)

**Comment by theharrisonmoore** [comment]
This is perfect!
-

Best,
Harrison Moore

**Comment by thejoefriel** [comment]
Hey @amusameh - on this issue, on the current PR add features-1 the feature hasn't been added for if admin is replying to individual comments on answers. Do you mind adding that too please?
