### ISSUE TITLE
The site still has old icons being used, instead of the new icons

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#672]
@thejoefriel The site still has old icons being used, instead of the new icons. The image below shows the new icons (the SVGs you prefer). But there are still old icons on the entity's profile pages and on the buttons when adding a new entity.

We're asking workers to wrap their heads around the concept of 'four entities' so we really need consistency with the icons.

![IMG_FA2956969460-1](https://user-images.githubusercontent.com/45825100/64865838-25a83400-d632-11e9-85a2-c214d6ce13ff.jpeg)

**Comment by thejoefriel** [comment]
@theharrisonmoore Is this purely
