### ISSUE TITLE
Uploaded worksite photos are displayed skewed 90 degrees

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#683]
@thejoefriel Uploaded worksite photos are displayed skewed 90 degrees

![IMG_2678](https://user-images.githubusercontent.com/45825100/64910683-fae0dd00-d710-11e9-8dfd-b54054a48118.JPG)

(Even the images I'm uploading to Github are being displayed skewed, too ;)

**Comment by RamyAlshurafa** [comment]
can't replicate this bug

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore none of us can replicate this bug. Can I just check what the orientation actually was of the original photo? What I've found is that if a user uploads a photo that isn't already orientated correctly it'll stay that way (as there's no way of us being able to know what the 'right' way is) but everytime we upload a photo it shows it exactly the same as how it looks on your phone when you uploaded it

**Comment by thejoefriel** [comment]
@RamyAlshurafa @theharrisonmoore I've looked into this a bit more and the issue seems to be if the user decides to take a photo (rather than uploading one) and takes the photo with their phone in portrait rather than landscape

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Yes, I took the picture in portrait
mode.
-

Best,
Harrison Moore
