### ISSUE TITLE
When using sliders, the whole screen moves both ways

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#687]
@thejoefriel When using sliders, the whole screen moves both ways.

iPhone 8, Safari

https://drive.google.com/open?id=1ZBTUl3Qj93sKelhR-gnzFFt8RTC0XsVI

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore - I've tried this and it seems to only be an iPhone issue as it works fine on all the devices we've tried. 

To confirm, it lets you use the slider and doesn't crash or anything, or make the app unusable (by the looks of it it bounces back when you let go of the slider) ? If so, do you think we could downgrade this to an enhancement?

The only reason I ask is that the user story can be completed and from an initial look it's going to take a long amount of time to dig into why apple devices do this as I spent the past hour and can't find anything covering this problem. 

Let me know your thoughts

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Sure, considering how much work you
guys have done and how supportive you've been, I'm happy to downgrade this
to an enhancement. As you say, it doesn't stop users giving a review so
it's not business-critical.
-

Best,
Harrison Moore

**Comment by thejoefriel** [comment]
Thanks @theharrisonmoore :)
