### ISSUE TITLE
These messages should also be displayed at the bottom of the page

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#692]
@thejoefriel These messages should also be displayed at the bottom of the page (right above the 'Publish' button) so that workers can see what to do when their review isn't being published.

While this may seem trivial, it's actually a critical part of earwig - gathering reviews. If a user has gone to the trouble of signing up, getting verified and completing a review, the last thing we want is for them to not understand why it's not being published and then give up at the final hurdle.

To be clear, these messages should appear both by the question itself and at the bottom of the page.

iPhone 8, Safari

Please change these messages to: 'Please select the work period'
![IMG_76CE2C4FEF58-1](https://user-images.githubusercontent.com/45825100/65059339-c027b080-d96d-11e9-9701-24a34920269c.jpeg)

Please change these messages to: 'Please give a star rating'
![IMG_C6DDE5EF00B0-1](https://user-images.githubusercontent.com/45825100/65059175-6e7f2600-d96d-11e9-8445-48edd5c8003a.jpeg)

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore - I don't believe this was something that was ever discussed before or shown in any wireframes? Sorry if I've missed this!

**Comment by theharrisonmoore** [comment]
You're right. It was not included. So this is an addition. It's critically
important though so really needs doing, feel free to charge extra if needed.
-

Best,
Harrison Moore

**Comment by thejoefriel** [comment]
We've done this for you @theharrisonmoore
