### ISSUE TITLE
In Admin, the 'City/Town' and 'Trade' columns don't appear to be recording data

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#696]
@thejoefriel In Admin, the 'Town/City' and 'Trade' columns don't appear to be recording data.

<img width="1440" alt="Screenshot 2019-09-17 at 18 22 55" src="https://user-images.githubusercontent.com/45825100/65064400-4fd25c80-d978-11e9-8c55-75800f667206.png">

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore this has been fixed. Just to note it'll still show N/A for some of the dummy users that are in there as that info isn't in the database to check various edge cases, but for all new users it will be shown fine.

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> great stuff, thanks.
-

Best,
Harrison Moore
