### ISSUE TITLE
I'm still receiving these error messages every day

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#699]
@thejoefriel I'm still receiving these error messages every day.

<img width="1440" alt="Screenshot 2019-09-22 at 16 55 58" src="https://user-images.githubusercontent.com/45825100/65390838-1fb10200-dd5a-11e9-9ff6-d36869483e06.png">

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore I've fine-tuned your sentry settings so this won't send you these for minor things, so you shouldn't be bothered by this now. I would also suggest that we make sure for sprint 3 we allocated time for us devs to go through the log to see where we should do further refactoring.

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Okay, sounds like a good plan.
-

Best,
Harrison Moore
