### ISSUE TITLE
I'm shown an error message when I try to visit earwig.work

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#706]
@thejoefriel I'm shown an error message when I try to visit earwig.work

iPhone 8, Chrome

https://drive.google.com/open?id=18X-jhBh7MEOBlgDDLPrwJ_myHh3n7yry

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore - I've gone on the website on a few browsers but can't replicate this issue. Are you still getting this?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> I cannot replicate this issue now. It
must have been because I was trying to access the earwig.work URL while you
guys were working on it.
-

Best,
Harrison Moore

**Comment by theharrisonmoore** [comment]
@thejoefriel I'm closing this issue now.
