### ISSUE TITLE
Small glitch on voice review button

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#708]
@thejoefriel Small glitches on voice review button. Read all the way to the bottom before troubleshooting.

Samsung S6, Samsung Internet

You can see in this first image that the button has a small glitch.

![IMG_0026](https://user-images.githubusercontent.com/45825100/65693531-55acf980-e06c-11e9-8107-dee7fdb9ebd5.jpg)

Also, once I've recorded a voice review, I cannot play it back before publishing.

However, when I gave a review about a different company, this time adding my own called 'Test Agency,' the glitch did not happen AND I was able to playback the voice review before I hit Publish. In fact, the voice playback module looked different from before. In the previous reviews, the module looked square and dark. Whereas the module in the image below is pill-shaped and grey, which is correct.

![IMG_0029](https://user-images.githubusercontent.com/45825100/65696324-ef76a580-e070-11e9-9dce-4a5d71037aec.jpg)

Hope that's not too confusing. Basically, when I gave a voice review before, there was a glitch with the button, the module looked different and I couldn't playback before publishing. Now when I try it on different companies, there's no glitch, the module looks better and I can playback before publishing. Not sure what's going on. I know you guys updated the voice module halfway through the sprint. I wonder if there's still the ghost of the previous module lingering about?

**Comment by thejoefriel** [comment]
@theharrisonmoore - I've tried this on Samsung device and can't replicate the bug. From what you're saying it happened once and then you haven't been able to replicate since?
