### ISSUE TITLE
I can approve or reject a worker verification photo (and therefore an account)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#71]
Relates to #70 

- [x] Give user prompt to confirm
- [x] On confirmation, change status of worker
- [x] Delete image

**Comment by thejoefriel** [comment]
@theharrisonmoore - on this, what happens if you reject a worker's photo? How is this conveyed to the user?

**Comment by theharrisonmoore** [comment]
They should receive an email. I can provide copy for all emails.

<https://signup.earwig.work/>

**Comment by theharrisonmoore** [comment]
@thejoefriel On second thoughts, there could be a number of reasons we reject a photo:

1. Photo is blurred
2. ID is dirty, damaged, illegible
3. Photo is not a person
4. Person is not including their ID
etc. etc.

So, ideally, the Dashboard would give me these options - buttons I'd click that would send the appropriate email. Now I know this is extra development. So, for now, don't give it any functionality. I will send the user an email myself.

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore thanks for this, makes sense in terms of you sending the email for now. What we can also do is render a 'catch-all' message on their profile page by the verified section that says the photo has been rejected and they should expect an email with more information - if not email X. What do you think?

**Comment by theharrisonmoore** [comment]
I'm not quite sure what you mean…

<https://signup.earwig.work/>
