### ISSUE TITLE
Voice reviews must not be downloadable

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#712]
@thejoefriel Voice reviews must not be downloadable.

Sorry, only just noticed this option hidden behind another button. This could lead to some quite serious legal problems for earwig if users were to download our IP and use it for their own purposes and companies took legal action against them. In our Terms of Use it states that all user-generated content is owned by the user but that they relinquish all rights solely to earwig for it to use how it pleases. It doesn't, however, say that user-generated content can be downloaded by other users. We'd end up in a legal nightmare. Can we remove the download button?

![IMG_0032](https://user-images.githubusercontent.com/45825100/65699794-872ac280-e076-11e9-8b5c-1337e5479e11.jpg)

**Comment by thejoefriel** [comment]
@theharrisonmoore - ok, I've looked into it and I've added a no download tag on the audio which removes the download option from the menu option on Chrome which by the looks of the screengrabs is what you found.

However, it is not possible to completely remove 100% the option for users to be able to download the audio: https://www.joomlacontenteditor.net/support/forum/91497-how-to-disable-the-download-option-for-html5-audio-player

The web audio has to be linked to a mp3 source, so even just inspecting the code would allow them to find the source file (this is how for example people rip audio from soundcloud, youtube etc). In the future we could do a tech spike to research how we make this as hard as impossible (we can't do any more on this though for this sprint as this isn't a bug, restricting download access is an extra feature). However from initial research it looks tricky to completely protect it so I would advise that you look into covering this within your T&Cs.

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore , this appears to have just been a typo on the first sentence, apologies. I've gone through the rest by each clause and it looks to me that other than this they are exactly the same. I've also checked through the cookie policy, and while there I've added some fixes to some spacing issues. 

I've pushed this up and we will merge back into master so it's fully in line. Sorry again for the concern.

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Hi Joe, thanks for jumping on this
quickly. Yeah, the lawyers said to re-upload (or re-copy & paste) all four
docs just as they are, without any typing, and then they'll be sound. Will
you be able to do this? We need to avoid typing altogether. Just copy and
paste what's on the page. It may seem trivial but it's really not. Those
four docs are all that stands between success and a court case and I just
know that people will find all manner of ways to undermine legal docs. They
need to be concrete.

I'll create a separate issue in GutHub now and attach the four docs.

-

Best,
Harrison Moore
