### ISSUE TITLE
As a worker giving a review, I can choose the date I was last there and the box highlights to show that a date has been chosen

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#730]
This is a change to the dates input during the review process. We no longer need to have two (from/to) date inputs. We only need one input.

**Changes**

- [x] Only one date input needed
- [ ] Update question text
- [x] Update placeholder
- [x] Highlight the box to show a date has been chosen
- [x] Make sure this is reflected accordingly in the database

<img width="782" alt="Screenshot 2019-11-04 at 13 33 09" src="https://user-images.githubusercontent.com/45825100/68124817-2067b700-ff08-11e9-93c2-5c83bb4c1122.png">

In Figma, refer to the page called _Updated date input_.

**Comment by RamyAlshurafa** [comment]
Hey @theharrisonmoore 

hope you are doing well,
in terms of this issue do we still need to disallow selecting the months that are before more than one year?

**Comment by theharrisonmoore** [comment]
@ramy@yallacooperative.com <ramy@yallacooperative.com> I'm great thanks.
Hope you're well too.

Could we make this three years?
-

Best,
Harrison Moore

**Comment by RamyAlshurafa** [comment]
@theharrisonmoore Yeah I'm fine too thanks.
No problem with 3 years
