### ISSUE TITLE
As a user/worker, I can click Tool Tips and see a popup. I can then close the popup by clicking 'Okay'

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#732]
There are some changes to the Tool Tips and some additional Tool Tips added.

**Changes**
Add a new Tool Tip (with icon) to the following places:
In Figma, refer to pages called:
- [x] Updated 'Sign in' page
- [x] Updated review questions
<img width="424" alt="Screenshot 2019-11-04 at 13 51 03" src="https://user-images.githubusercontent.com/45825100/68125769-32e2f000-ff0a-11e9-849c-7a6633957054.png">

- [x] Add new icon in front of _every_ Tool Tip ([Link to folder containing icons](https://drive.google.com/open?id=1rtzCm0edRuuJSHWSuHiGWBlohnPEQUGJ))
<img width="312" alt="Screenshot 2019-11-04 at 13 48 15" src="https://user-images.githubusercontent.com/45825100/68125565-c7991e00-ff09-11e9-912f-f5891069bc91.png">

As always, please ensure consistency across both mobile and desktop.

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore -  I realised this should also be on the profile page if they're not allowed to write a review, correct?

**Comment by theharrisonmoore** [comment]
@thejoefriel No, I don't think so. The first Tool Tip (How can you make your reviews helpful…) should only be on the giving a review page.

The second Tool Tip (What trade ID…) should only be on the getting verified pages.

-

PS You'll find another popup on the getting verified pages (Thanks, we're checking your photo…) that _looks_ like a Tool Tip, but it's not. This is a popup users' see when they hit Finish and log in. Does that make sense?

**Comment by thejoefriel** [comment]
Sorry @theharrisonmoore I don't think I was clear. What I meant is that the "Why can't I give reviews?" should look the same as the standard tool tip

i.e.
![image](https://user-images.githubusercontent.com/19708921/68383189-1682c580-014d-11ea-8f0b-91aea9eaa63a.png)

**Comment by theharrisonmoore** [comment]
@thejoefriel Oh yes! Yes, that's right. Thank you for spotting that!

**Comment by thejoefriel** [comment]
No worries :)

**Comment by theharrisonmoore** [comment]
@thejoefriel Can you change the Tool Tip to say, 'Why can't I give a review today?'

And the popup that appears should say, 'You recently reviewed this (…). Please leave four weeks between reviews.'

Joe, please make the popup specific to the context its in, ie agency, payroll, worksite or company.

**Comment by theharrisonmoore** [comment]
@thejoefriel There is a Tool Tip missing from the agency review
<img width="300" alt="Screenshot 2019-11-14 at 06 28 36" src="https://user-images.githubusercontent.com/45825100/68832182-2ef06400-06a8-11ea-8fa6-05d2b43a3215.png">

**Comment by thejoefriel** [comment]
I've carried out these fixes and will put up 👍

**Comment by theharrisonmoore** [comment]
@thejoefriel I've checked and these are done, thanks. I'm going to close this issue.
