### ISSUE TITLE
Updates to review questions and profiles

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#734]
There have been a number of questions removed, re-ordered and changed on all four types of review, and some design changes, too.

**Changes**
In Figma, refer to the page called _Updated review questions_.

I have updated the questions and their flows in both Whimsicle and in the [Main Sheet](https://docs.google.com/spreadsheets/d/1FYGTogNHkA85wl2gR2NrLbba2Nt5onO6DhI_OoIDSJw/edit#gid=1423776411).
New Agency question flow: ![agency flow latest](https://user-images.githubusercontent.com/45825100/68197976-18b11c80-ffb3-11e9-9ab0-ba086541bf2b.png)

New Payroll question flow: ![Payroll question flow](https://user-images.githubusercontent.com/45825100/68127126-201dea80-ff0d-11e9-9434-d2190672de73.png)

New Worksite question flow: ![Worksite flow](https://user-images.githubusercontent.com/45825100/68127151-3035ca00-ff0d-11e9-8e09-2a09d05a2f51.png)

New Company question flow: ![Company flow](https://user-images.githubusercontent.com/45825100/68127205-50658900-ff0d-11e9-97a9-ced0b944ef08.png)

- [x] Update _all_ review question text
- [x] Ensure new date input in incorporated (see Issue #730 )
- [x] Ensure any Tool Tips are incorporated
- [x] Remove unwanted questions
- [x] Ensure questions are in the correct order and that any logic works correctly
- [x] Update placeholder in comments box
<img width="477" alt="Screenshot 2019-11-04 at 14 26 53" src="https://user-images.githubusercontent.com/45825100/68128212-3036c980-ff0f-11e9-832e-9c89b2db776b.png">

Likewise, the way that answers are rendered on the entity profiles has also been updated. In Figma, please refer to the page called _Updated profile pages_.

- [x] Update all answers and data bars
- [x] Remove unwanted answers
- [x] Ensure that answers are displayed in the order consistent with the wireframes

**Design changes**
- [x] Add a warning icon to the voice review module and colour the warning text yellow
[Link to the folder with icons](https://drive.google.com/drive/folders/1rtzCm0edRuuJSHWSuHiGWBlohnPEQUGJ?usp=sharing)
<img width="429" alt="Screenshot 2019-11-04 at 15 03 54" src="https://user-images.githubusercontent.com/45825100/68131145-6b87c700-ff14-11e9-8656-7bd493078eaa.png">

- [x] Add placeholder to review text box
<img width="399" alt="Screenshot 2019-11-04 at 15 05 51" src="https://user-images.githubusercontent.com/45825100/68131249-a12cb000-ff14-11e9-82e1-847697c64758.png">

As always, ensure this is done on both mobile and desktop.

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore - we've noticed that the question flow above (e.g. for agency) has nested logic - i.e. there are two routes you can go based on saying yes no and then within that route there is another split before it all joins up again. 

We currently do not have this intricacy of logic built into the system as it's quite complex. We can do one split in the flow (as you've seen in the existed work). Is there anyway of simplifying this flow again?

Here's the section:

![image](https://user-images.githubusercontent.com/19708921/68196021-da662e00-ffaf-11e9-9d3f-be841cf8eda9.png)

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> I see. To make things easier, let's
get rid of the question 'Did this agency send you a contract before your
work started'… for now. We can look at fitting it back in another time.

I'll remove it from the designs now
-

Best,
Harrison Moore

**Comment by thejoefriel** [comment]
OK thanks @theharrisonmoore :) If you paste in the updated flow once it's ready as a comment that'd be perfect. I think it's only the Agency flow that has this extra nested logic?

**Comment by theharrisonmoore** [comment]
Done (I've replaced it)

**Comment by theharrisonmoore** [comment]
@thejoefriel @amusameh This question needs updating to say, 'This agency works with the following payroll companies.'
![IMG_E6AA29729248-1](https://user-images.githubusercontent.com/45825100/68832494-fef59080-06a8-11ea-9c00-257fa7ba9043.jpeg)

**Comment by thejoefriel** [comment]
I have fixed these and will push up :+1:

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore sorry on this one:

![image](https://user-images.githubusercontent.com/19708921/68854202-b339fa00-072f-11ea-97a0-cf6b92efc1a4.png)

Are you saying the overall question needs to go above the two payroll questions?

**Comment by thejoefriel** [comment]
Also on this one @theharrisonmoore the correct spelling is 'You're' as it's saying "You are", isn't it?

Also, check the spelling of the word 'your'

**Comment by theharrisonmoore** [comment]
@thejoefriel I think you are reading the task and mistakenly associating it with the image above instead of below it?

**Comment by theharrisonmoore** [comment]
@thejoefriel This is the word I'm talking about:
<img width="608" alt="Screenshot 2019-11-14 at 12 25 00" src="https://user-images.githubusercontent.com/45825100/68857038-d639bf00-06d9-11ea-8362-b610c2a1dd8c.png">

**Comment by thejoefriel** [comment]
OK so it's the getting yor wages typo not the you're that the arrow is pointing at. Thanks for clarifying. Will fix that now

**Comment by theharrisonmoore** [comment]
@thejoefriel The popout comments box is missing from this question:
![IMG_0196](https://user-images.githubusercontent.com/45825100/68989114-3f384880-083a-11ea-8178-c1c6a4755651.jpg)


This heading 'Getting your wages' should be higher up the page. And this question 'What's the name of the agency you used?' should be higher up the page. Please see wireframes.
![IMG_0197](https://user-images.githubusercontent.com/45825100/68989202-e4532100-083a-11ea-8916-a0dedc6e075e.jpg)


This question should not have a comments box
![IMG_0199](https://user-images.githubusercontent.com/45825100/68989253-925ecb00-083b-11ea-9e28-6188159e99bd.jpg)
