### ISSUE TITLE
As a user, I can navigate between four different search pages

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#737]
There has been a change in the way users search for entities. Instead of having just the one page and search bar, we need to have four distinct pages.

There are also changes to the Welcome page.

In Figma, refer to the page called _Updated search page_.

- [x] Discard icons for the organisation search results
- [x] Ensure entities are listed in A-Z order down each page
- [x] Ensure the search bar and buttons are fixed when scrolling
- [x] Ensure the search bar is only querying its appropriate list of entities, eg only agencies should be searchable from the agency search page
- [x] Ensure the A-Z list of entities is only for that type of entity eg only agencies should be listed on the agency search page
- [x] Ensure the new 'adding to a list' design is used (relates to Issue #729 )
- [x] Update Welcome page design and buttons
- [x] Update 'Adding new entity' pages

Please ensure consistency across both mobile and desktop.

**Comment by theharrisonmoore** [comment]
@thejoefriel @RamyAlshurafa A-Z should come first at the top of the page, followed by 0-9

**Comment by theharrisonmoore** [comment]
@thejoefriel @RamyAlshurafa I found a small bug during user-testing: When new entities have been added to the database, they are not displayed in the A-Z list.

For example, prior to the user-testing session, I created a new company called 'ABC Civils,' which I then asked each user to find and give a review about. But despite my having added it, the users could not find it in the A-Z list and had to use the search bar instead. Please can you fix this?

Many thanks

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore I've set this up as a new issue (https://github.com/yalla-coop/earwig/issues/813) so will close this one to keep things simple
