### ISSUE TITLE
Create new common component that lets you scroll back to the top

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#739]
_Acceptance criteria still to be agreed_

- [ ] Add a button to the bottom of pages that when clicked, scrolls users to the top of the page
<img width="283" alt="Screenshot 2019-11-04 at 15 01 34" src="https://user-images.githubusercontent.com/45825100/68130866-07650300-ff14-11e9-85fc-c08e6c452759.png">

**Comment by theharrisonmoore** [comment]
@thejoefriel I'm closing this issue as it's not important at this stage.
