### ISSUE TITLE
Updated wireframes

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#741]
These are the signed off wireframes for issues #737 #784 #787 #788 #791 #792 #793 #794 #795 #796 #800 #801 #802 

**DESKTOP**
https://www.figma.com/file/7Nr7QP1vGHSpDJlPdeSDll/Chunk-1-Desktop

**MOBILE**
https://www.figma.com/file/UodKxxrG0s5089bR6cGiOX/Chunk-1-Mobile?node-id=0%3A1

**Comment by thejoefriel** [comment]
@theharrisonmoore Do you mind double checking that you're happy with how everything has been imported into Figma please?

**Comment by theharrisonmoore** [comment]
Yes, can you send me links to the new Figma pages?
-

Best,
Harrison Moore

**Comment by theharrisonmoore** [comment]
Sorry, I got them in Github
-

Best,
Harrison Moore

**Comment by theharrisonmoore** [comment]
@thejoefriel @amusameh @RamyAlshurafa All looks good!

Good luck team! Send me messages in the #development Slack channel any time
