### ISSUE TITLE
Bug: Upload verification image throw an error

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/earwig#752]

**Comment by RamyAlshurafa** [comment]
@thejoefriel 
I tried to replicate this but I couldn't
could you record a video of what you got?

**Comment by thejoefriel** [comment]
@RamyAlshurafa sure thing here you go: https://www.loom.com/share/a58e81ebb5f24367969efa2456912e9b

**Comment by thejoefriel** [comment]
So to confirm, there's no problem uploading the image for verification when you sign up as a worker the very first time you sign up. The bug appears if the user has already created an account as a non-worker, then chooses to get verified as a worker. Maybe there's an issue with updating their status from non-worker to worker?

**Comment by RamyAlshurafa** [comment]
We agreed to close this issue since we can't replicate it, can be open again if the bug occurred
