### ISSUE TITLE
We can't get the star rating to sometimes appear above the bar chart

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#759]
Hi @theharrisonmoore - we are struggling to get the star rating to sometimes appear above the bar graphs as outlined in the updated wireframes. 

Creating this issue so we can decide where on the priority list this is

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore - how much of a priority is this? And if it is something to work on in this chunk, can you let us know if there are meant to be questions that appear above the bar for worksite, company or payroll? We only have agency in the wireframes. And if so, which questions. Thanks!!

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> I don't know what you're referring to
as there's no accompanying image. Can you take a screenshot?

**Comment by theharrisonmoore** [comment]
@thejoefriel We've spoken and agreed that star ratings should always be the first thing the user sees. I'm now closing this issue.
