### ISSUE TITLE
I can delete Agencies, Payrolls, Worksites, and Companies from the public platform (this would also delete any reviews related to that profile) by marking it as deactivated

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#77]
Relates to #76 

- [x] Add deactivate button
- [x] Deactivating changes status of organisation to deactivated

**Comment by thejoefriel** [comment]
@theharrisonmoore - would you want the reviews and organisation deleted from the database or kept on there?

**Comment by theharrisonmoore** [comment]
I would never want any of the review data to be *deleted* - it's the most
valuable aspect of earwig. But, I do need the option to *remove* reviews
(or parts of reviews) from the front-end if I have to, which I understand
you've given functionality for.

In terms of data being deleted if and when we remove an entity profile,
again, I wouldn't want any of the review data to be actually deleted. In
the event I have to remove a profile, could the review data remain on the
back-end? If not, I would need the ability to export the data as a CSV file
before removing the profile.

<https://signup.earwig.work/>
