### ISSUE TITLE
Car parking cost is not rendering on worksite profiles

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#775]
@thejoefriel Car parking cost is not rendering on worksite profiles.
![IMG_0169](https://user-images.githubusercontent.com/45825100/68854354-c7500e00-06d3-11ea-8486-6983b73acb11.jpg)

Samsung S6, Samsung Internet

**Comment by theharrisonmoore** [comment]
@thejoefriel This is still not rendering.

Also, please bear in mind it's supposed to be rendered as '£X per day' not just '£X'

**Comment by thejoefriel** [comment]
Sorry @theharrisonmoore the database needed to be rebuilt. I've done this now and tested on the dev version and it's working fine. Will close for now but let me know if you're still hitting any issues
