### ISSUE TITLE
This page copy needs updating

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#783]
@thejoefriel 

- [x] This page copy needs updating (check across all signup pages).
![IMG_0171](https://user-images.githubusercontent.com/45825100/68921144-99200c00-076f-11ea-91b7-07ab7b901b30.JPG)

- [x] This copy also needs updating (check across all signup pages)
![IMG_0174](https://user-images.githubusercontent.com/45825100/68921671-5fe89b80-0771-11ea-8b49-1cb3436e3e01.jpg)

- [x] This placeholder should say 'Choose your trade'
![IMG_0172](https://user-images.githubusercontent.com/45825100/68921466-c3be9480-0770-11ea-963e-7979f3d70daf.jpg)

- [x] This button's width needs to be consistent with the new button designs
![IMG_0173](https://user-images.githubusercontent.com/45825100/68921564-0f713e00-0771-11ea-9099-9a156e915363.jpg)

**Comment by thejoefriel** [comment]
Hi Harrison what was the flow that took you to this page? I had removed his
per our conversation so working out how it's still there

**Comment by theharrisonmoore** [comment]
> Hi Harrison what was the flow that took you to this page? I had removed his
per our conversation so working out how it's still there.

@thejoefriel I signed up as non-worker, browed the site for a bit, then tried to give a review, which took me to my profile page. On this page there is a message and a button to get verified. This then took me to the page in question. This page _should_ exist as it's a page for getting verified only, not adding all the other stuff like email and password.

**Comment by thejoefriel** [comment]
Yeah I just remember on the phone you said you actually felt this shouldn't be in the flow. It's fine. I'll update the copy now 👍

**Comment by thejoefriel** [comment]
Oh I think on your screengrab you're on the user profile but have scrolled down which makes it look like the original wireframe you had in that you then removed.

**Comment by thejoefriel** [comment]
OK @theharrisonmoore these have been done and should be merged into the develop branch as soon as they are approved by the team here 👍

**Comment by theharrisonmoore** [comment]
Okay great

**Comment by theharrisonmoore** [comment]
@thejoefriel I've checked and these are all done, thanks. I'm going to close this issue.
