### ISSUE TITLE
During user-testing Admin was shown '500 internal server error' message when verifying a worker photo

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#789]
@thejoefriel During user-testing, Admin was shown a '500 internal server error' message when verifying a worker photo. Obviously I'm still user-testing for the rest of the day so can this wait until tomorrow?

Thanks

**Comment by amusameh** [comment]
@theharrisonmoore I'll look into this and let you know shortly

**Comment by amusameh** [comment]
@theharrisonmoore I can't replicate this locally or on heroku 
If the user gets verified even with 500 error getting thrown then I think it won't be a problem.
I'll check more on this in the meantime.
Please let me know if this happens for all users

**Comment by theharrisonmoore** [comment]
@amusameh I didn't encounter this issue again. It only happened once this morning.

I'll close the issue now.
