### ISSUE TITLE
Updates to reviewing pages

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#791]
We must make updates to the reviewing pages in the following ways:

**Payroll reviewing page**
- [x] Remove heading
![IMG_0209](https://user-images.githubusercontent.com/45825100/69250649-fb31a480-0ba7-11ea-93e4-4d11b73febe1.jpg)

**Company reviewing page**
Please refer to this updated question flow: https://whimsical.com/GnoVqKG7Wtr8gHEyYeNheY
- [x] Remove question 'Was this company’s materials store well organised?'
- [x] Remove question 'Did this company offer you access equipment when you needed it?'
- [x] Remove question 'Was the access equipment in safe condition?'
- [x] Remove question 'Did you feel valued working for this company?'
- [x] Change question from 'Did you feel the supervisor shared all the information you needed to do a good job?' to 'Did you feel the supervisor shared all the information you needed to complete your tasks?'
- [x] Add new question 'Did this company offer you all the equipment and materials you needed to complete your tasks?'
- [x] Add new question 'Did you feel this company asked you to work unsafely?'
- [x] Sequence all questions as per wireframes
- [x] Ensure questions are updated accordingly in back-end database when exporting

**All reviewing pages**
- [x] When user clicks to give a star rating, change the colour of the filled stars from grey to yellow
<img width="262" alt="Screenshot 2019-11-20 at 14 18 41" src="https://user-images.githubusercontent.com/45825100/69246612-eef61900-0ba0-11ea-8884-9029a36fc6ca.png">
-

- [x] Update placeholder text in review text box
<img width="265" alt="Screenshot 2019-11-20 at 14 21 09" src="https://user-images.githubusercontent.com/45825100/69246683-0df4ab00-0ba1-11ea-8d1f-ed68d94b4761.png">
-

- [ ] Tool Tip icon needs to be a consistent size throughout. Not small like this:
![IMG_0139](https://user-images.githubusercontent.com/45825100/68683969-9bac1700-055f-11ea-8fcb-12257f852334.jpg)

Please refer to the page called 'Updated reviewing pages' in the wireframes.
Ensure consistency across both mobile and desktop.

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore with "remove heading" - does this just refer only to the General heading in payroll review specifically? Or is it removing all section headings?

**Comment by thejoefriel** [comment]
>  Add new question 'Did this company offer you all the equipment and materials you needed to complete your tasks?'
>  Add new question 'Did you feel this company asked you to work unsafely?'

Are these questions Yes / No questions?

**Comment by thejoefriel** [comment]
>  Tool Tip icon needs to be a consistent size throughout. 

I would suggest we put this as a separate issue as this is updating a common component rather than the review page. What do you think @RamyAlshurafa @amusameh @dupreesi

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> I think your questions are because
you don't yet have the new wireframes, which I'm ready to send you, but I
just need to know what format you need them in.

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore , it would be the same as usual please so sketch files I guess to I can import them into Figma. Thanks!
