### ISSUE TITLE
Remove question-specific commenting altogether

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#792]
We must remove all question-specific commenting from both review-giving pages and entity profile pages.

- [x] Remove all comments text boxes from reviewing pages
- [x] Remove all 'Comments' buttons from entity profile pages
- [x] Ensure this is updated in the back-end database for exporting

**Comment by thejoefriel** [comment]
So to check on this @theharrisonmoore the comment box will no longer appear each time the user answers a question?

Design-wise on the profile would the answer just be wider to fill this space where the comment box previously was?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> We are removing the ability to
comment on specific questions altogether. So the only place where users can
write reviews is at the end in the overall review box.
