### ISSUE TITLE
Update error messages on sign up

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#795]
We must clearly show users signing up the correct error messages when they leave fields blank or their passwords don't match, and we must show the appropriate error messages at the _bottom_ of the page as well as by the field.

Please refer to the page called 'Error messages on sign up' in the wireframes.

**Note:**
Town or City field is not compulsory

**Comment by thejoefriel** [comment]
OK so @theharrisonmoore to confirm, the tasks for this issue are:

- Update the error messages to match those shown in the wireframes
- Change Town or City so it is no longer a required field

Is that right?

Also do you have updated wireframes we're meant to be using, or are these still correct? 
https://github.com/yalla-coop/earwig/issues/741

I can't see the 'Error messages on sign up' page on these wireframes - where are they?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Yes, that is correct.

I'm ready to send you the new wireframes but I just need to know what
format you need them in…

**Comment by thejoefriel** [comment]
For reference on this issue, this question about wireframes is answered in https://github.com/yalla-coop/earwig/issues/791
