### ISSUE TITLE
Updates to Welcome, and Search page designs

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#801]
Please make the following design changes to the Welcome page and the Search pages:

**Welcome page**
- [x] Remove earwig logo from the header bar
- [x] Add background image (image is in this folder: https://drive.google.com/open?id=1rtzCm0edRuuJSHWSuHiGWBlohnPEQUGJ).
- [x] Add white logo (see the same folder)
- [x] Add new heading (font size 24 and **bold**)
- [x] Add new text (font size 15 and regular)
- [x] Add buttons (with arrows)
- [x] Ensure each button navigates to its corresponding search page

**Search pages**
- [x] Remove large headings
- [x] Ensure the coloured area surrounding search bars is not too deep
- [x] Ensure buttons and search bar remain fixed when user scrolls (but _not_ the main header bar)

Please refer to the page called 'Updated search pages' in the wireframes.
Ensure consistency across both mobile and desktop.

**Comment by dupreesi** [comment]
@theharrisonmoore do you want the search bar/ buttons also be fixed on mobile when user scrolls?

**Comment by theharrisonmoore** [comment]
@dupreesi Yes please, exactly like the wireframes in Figma.

**Comment by dupreesi** [comment]
OK done!
