### ISSUE TITLE
Updates to all other pages

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#802]
We must update the following pages in the following ways:

**Invite workers to earwig page**
- [x] Add new text
- [x] Update buttons

**Your profile page**
- [x] Ensure reviews, helped and points counters are rendered horizontally not vertically
<img width="267" alt="Screenshot 2019-11-20 at 14 30 31" src="https://user-images.githubusercontent.com/45825100/69247534-6d9f8600-0ba2-11ea-8b08-eb20b2c89ac2.png">
-

**Change your trade page**
- [x] Update placeholder text to 'Choose your trade'
<img width="256" alt="Screenshot 2019-11-20 at 14 32 39" src="https://user-images.githubusercontent.com/45825100/69247650-a17aab80-0ba2-11ea-8e4b-7282e2d8530a.png">
-

**Reviews you've given page**
- [x] Update buttons
<img width="243" alt="Screenshot 2019-11-20 at 14 33 35" src="https://user-images.githubusercontent.com/45825100/69247727-ca02a580-0ba2-11ea-9c0b-6966cb3e035d.png">

- [x] Add hyperlinks to entity names
- [x] Remove icons

**FAQ page**
- [x] Remove icon

**Helpful stuff page**
- [x] Remove icon

**Privacy & terms page**
- [x] Remove icon

Please refer to the page called 'Updated all other pages' in the wireframes.
Ensure consistency across both mobile and desktop.

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore on "Reviews you've given page" while we're making changes, I feel it would be good to make the entity name a link to that entity profile. What do you think? Is this something that came up at all in user testing? The reason I suggest this is when I was adding reviews, and wanted to find them again, it was frustrating having to see the review I've given, then go to the search page and find the entity, rather than just being able to click through. 

Also, do you want us to remove the icons too?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> Yes please!

- [ ] Add hyperlinks to entity names
- [ ] Remove icons

**Comment by thejoefriel** [comment]
OK cool! I'll add these to the overall issue

**Comment by thejoefriel** [comment]
PS do you mind updating the wireframe so it's clear how you want it to look with the icon removed and what colour your want the entity link to be?

**Comment by theharrisonmoore** [comment]
I'll do that now and resend you the wireframes

**Comment by amusameh** [comment]
Hi @theharrisonmoore 
In the new wireframe the Large Heading is deleted, Do you want me to delete it?
![Screenshot from 2019-11-26 16-22-18](https://user-images.githubusercontent.com/28042978/69642266-2ade2200-106a-11ea-811a-3b5cde2e677f.png)

And what about this page:(the heading and the icon), Do you want me to delete it as well?
![Screenshot from 2019-11-26 16-32-53](https://user-images.githubusercontent.com/28042978/69642474-78f32580-106a-11ea-8c57-ba944accbf63.png)

**Comment by theharrisonmoore** [comment]
@amusameh Yes please, exactly like the wireframes in Figma.
