### ISSUE TITLE
Updated wireframes (Chunk 2)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#803]
These are the wireframes for the following issues:
#737 #784 #787 #788 #791 #792 #793 #794 #795 #796 #800 #801 #802

**DESKTOP**
https://www.figma.com/file/oCZJ6w6RFUKJxi3kd83Ja8/Chunk-2-Desktop

**MOBILE**
https://www.figma.com/file/BB1jvZ1Bkj5oCPwNqulZPk/Chunk-2-Mobile

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
not all the Figma components are displayed for me can you upload another copy?

**Comment by thejoefriel** [comment]
Sure thing @RamyAlshurafa Have changed it now in the main description. Let me know if any better

**Comment by RamyAlshurafa** [comment]
thanks @thejoefriel 
unfortunately, they are the same, can you share the pdf copies?
