### ISSUE TITLE
Update the reviews look and functionality on profile page

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#805]
This is the written and voice review section on the profile pages

- [x] Update 'Helpful' and 'Reply' buttons
- [x] Make 'Helpful' button fill grey when clicked
<img width="301" alt="Screenshot 2019-11-20 at 14 44 34" src="https://user-images.githubusercontent.com/45825100/69248507-52357a80-0ba4-11ea-95fb-3e384558517f.png">

- [x] Move the _review_ author's username and stats to below their review (but don't move the position of _replies_ author's username and stats)
<img width="244" alt="Screenshot 2019-11-20 at 14 40 30" src="https://user-images.githubusercontent.com/45825100/69248207-c3286280-0ba3-11ea-8830-59232765e4e2.png">

- [x] Add star ratings from each worker beside their username and stats
<img width="316" alt="Screenshot 2019-11-19 at 13 51 45" src="https://user-images.githubusercontent.com/45825100/69152110-c9e7a480-0ad3-11ea-8e3d-942dc094fa50.png">

- [x] Keep usernames and stats from replies as they are (_above_ their reply)
<img width="391" alt="Screenshot 2019-11-20 at 14 42 46" src="https://user-images.githubusercontent.com/45825100/69248373-18fd0a80-0ba4-11ea-8a47-91e66cd58fe1.png">

- [x] Ensure there are faint lines separating each review
<img width="323" alt="Screenshot 2019-11-19 at 14 01 33" src="https://user-images.githubusercontent.com/45825100/69152904-2a2b1600-0ad5-11ea-8976-1e19e4a8a544.png">

**Comment by RamyAlshurafa** [comment]
Hey @theharrisonmoore 
what the disabled `Reply` button should look like?

**Comment by theharrisonmoore** [comment]
@RamyAlshurafa The Reply button should remain the same whether or not it has been pressed. Users can give as many replies as they like.
