### ISSUE TITLE
Update profile design

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#807]
Please do not work on this until issues #805 and #806 are completed

- [x] Update overall layout of profile pages
- [x] Reorder the sequence of data bars in Worksite profile
- [x] Reorder the sequence of data bars in Company profile
- [x] Ensure title fonts are size 18 and **bold**
- [x] Ensure subtitle fonts are size 15 and **bold**
- [x] Ensure all other fonts are size 15 and regular
- [ ] Ensure empty profiles designs are updated to reflect new changes
- [ ] Ensure everything matches the 'Updated profile pages' designs in the wireframes.
- [x] Ensure consistency across both mobile and desktop.
- [ ] Ensure opacity of profile fonts match the designs

**Comment by RamyAlshurafa** [comment]
Hey @theharrisonmoore 
I see that you use low contrast fonts in figma with 80% opacity for questions and titles. 
just wanted to check if you need that to be updated

**Comment by theharrisonmoore** [comment]
@RamyAlshurafa Yes please

**Comment by RamyAlshurafa** [comment]
@theharrisonmoore 
Will do :+1: 
for the empty profile layout, can you update the design to show us how the `Getting on to site ` and `The site welfare` ... should look?

**Comment by theharrisonmoore** [comment]
@RamyAlshurafa Figma won't let me create and edit. Instead, I've created a wireframe is Sketch and exported it here as a JPEG. Hope that's okay?

![Worksite profile (empty)](https://user-images.githubusercontent.com/45825100/69642770-31fd3400-105a-11ea-9512-bca86b64a5d2.jpg)

**Comment by RamyAlshurafa** [comment]
thanks @theharrisonmoore
