### ISSUE TITLE
Worksite profile not rendering

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#822]
From looking into it this is because we're filtering the questions based on "Working on this site" but in the database it's actually "Working on the site"

I will change back. However, if we need to change to Working on this site, we need to think what's the best way to change it on the database without rebuilding? Or is that our only option?

https://www.loom.com/share/b554c123177547e2b87276d46e0a5bfd

**Comment by theharrisonmoore** [comment]
@thejoefriel I think this is fine as it is now. Let's close this issue as I'm not experiencing problems any more.
