### ISSUE TITLE
Give review crashing due to navbar query

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#823]
It can't find the navbar query select on componentwillunmount which crashes the app

https://www.loom.com/share/788c8a74ccf44638b5d3e686c0ce31cb

**Comment by theharrisonmoore** [comment]
@thejoefriel I'm not experiencing any problems when giving reviews now. Not sure if you want to close this issue?

**Comment by RamyAlshurafa** [comment]
@theharrisonmoore 
Joe already fixed this
