### ISSUE TITLE
Icons sometimes not rendering (plus poor quality)

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#827]
@thejoefriel Sometimes these social share icons do not render for several minutes and when they do, they're poor quality. Please use the new SVG icons I've added to the folder: https://drive.google.com/drive/folders/1rtzCm0edRuuJSHWSuHiGWBlohnPEQUGJ

![IMG_E929B2030738-1](https://user-images.githubusercontent.com/45825100/69700821-52bd9c00-10e3-11ea-9a11-eaef4f234735.jpeg)

iPhone 8, Chrome

**Comment by thejoefriel** [comment]
Hey @amusameh did you want to pick up this issue again since you started it?
