### ISSUE TITLE
Please add Search icon to main header bar on all pages

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#834]
@thejoefriel Please add the Search icon to the main header bar on all pages and hyperlink it to the Welcome page.
This should be on all pages throughout the app except for the Welcome page itself.
Ensure the icon is grey (not blue like in the menu).

<img width="387" alt="Screenshot 2019-11-28 at 07 49 13" src="https://user-images.githubusercontent.com/45825100/69787184-dfd02600-11b3-11ea-9527-21317dc38285.png">
<img width="285" alt="Screenshot 2019-11-28 at 07 49 28" src="https://user-images.githubusercontent.com/45825100/69787185-dfd02600-11b3-11ea-88e7-cddde8719c95.png">
<img width="224" alt="Screenshot 2019-11-28 at 07 49 57" src="https://user-images.githubusercontent.com/45825100/69787186-dfd02600-11b3-11ea-8e17-f96c34efcc28.png">

**Comment by RamyAlshurafa** [comment]
Hey @theharrisonmoore 
what to put instead of the search icon on the welcome page? or keep it empty?

**Comment by theharrisonmoore** [comment]
@ramy@yallacooperative.com <ramy@yallacooperative.com> please keep it empty.

Best,
Harrison Moore
Sparky & founder
*earwig <http://earwigwork.com>*
