### ISSUE TITLE
Tabs are not fixed when scrolling worksite profile page

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#853]
@thejoefriel The two tabs are not fixed when scrolling worksite profile page.
https://drive.google.com/open?id=1uFNomqGNcyhMGyA55wlDGJXghoUtIoES

Samsung S6, Samsung Internet

**Comment by thejoefriel** [comment]
Hmm I'm not getting the same issue on my phone. @RamyAlshurafa have you any thoughts on this?

**Comment by RamyAlshurafa** [comment]
@thejoefriel yeah I got the same as the video only on Samsung internet default browser,
Im fixing it
