### ISSUE TITLE
Updated signup pages

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#856]
We need to make the following design tweaks to the signup pages:

Note: please refer to the page called 'Updated signup pages' in wireframes.

- [x] Replace Beta logo with normal logo
- [x] Remove second password field
- [x] Add 'Show password' check box
- [x] Remove 'Town or city' field but keep it in the Your Profile section.
- [x] Update heading and text about verification photo
- [x] Change Tool Tip to say 'Learn More'
- [x] Change Tool Tip text
- [x] Change button from 'Finish and log in' to 'Done.'
- [x] Remove 'Continue without signing up' link.
- [x] Add 'Back' button in top left corner.
- [x] Update Ts & Cs text

Ensure consistency across both mobile and desktop.

**Comment by amusameh** [comment]
Hi @theharrisonmoore 
I can't find the normal earwig logo svg with high quality (the wire-frames still have the beta version)
Can you please point me to the one you want to use?
thanks

**Comment by theharrisonmoore** [comment]
@abdalsamad.y.m@gmail.com <abdalsamad.y.m@gmail.com> I've just added it to
this folder:
https://drive.google.com/drive/folders/1rtzCm0edRuuJSHWSuHiGWBlohnPEQUGJ

Best,
Harrison Moore
Sparky & founder
*earwig <http://earwigwork.com>*

ᐧ

**Comment by amusameh** [comment]
Hi @theharrisonmoore 
>Protecting you from blacklisting
do you want this paragraph deleted from the signup page?

**Comment by theharrisonmoore** [comment]
@abdalsamad.y.m@gmail.com <abdalsamad.y.m@gmail.com> please refer to the
wireframes. I'm currently not able to look at it on my computer. Thanks!

Best,
Harrison Moore
Sparky & founder
*earwig <http://earwigwork.com>*

ᐧ
