### ISSUE TITLE
Updated wireframes (Chunk 3)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#869]
Here are the latest wireframes:
https://www.figma.com/file/AiJgLzLE1Gu9BBKBogD3rk/Chunk-3-Mobile?node-id=0%3A5303

These wireframes are for issues: #868 #867 #866 #865 #864 #863 #862 #861 #860 #859 #858 #857 #856 #855

**Comment by theharrisonmoore** [comment]
@thejoefriel I've added all the relevant issues here.
