### ISSUE TITLE
This question should always be asked, not hidden

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#896]
@thejoefriel This question should always be asked, not hidden. At the moment, it disappears when the previous question is answered as 'Yes.' But it should always appear.
![IMG_0289](https://user-images.githubusercontent.com/45825100/70794323-4ef17100-1d95-11ea-80d3-442973d3c0f1.jpg)

**Comment by thejoefriel** [comment]
@amusameh are you able to look at this one please? you've worked the most on the validation logic here so I think you'd be quickest to fix this.
