### ISSUE TITLE
New pop-up modals

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#903]
@thejoefriel New pop-up modals should appear when Level 1 or level 2 users try to click 'Like,' 'Reply' and 'Report.'

Please refer to the page called 'New popup modals' in the wireframes.

**Popup modals for Level 1 users**
- [x] When I click 'Like,' I should see the popup modal called 'Like popup.'
- [x] I can click 'Get verified' to be taken to the sign up/verification page. After signing up or getting verified, I should be brought back to this entity profile page.
- [x] When I click 'Reply,' I should see the popup modal called 'Reply popup.'
- [x] I can click 'Get verified' to be taken to the sign up/verification page. After signing up or getting verified, I should be brought back to this entity profile page.
- [x] When I click 'Report,' I should see the popup modal called 'Report popup.'
- [x] I can click 'Sign up' to be taken to the sign up/verification page. After signing up or getting verified, I should be brought back to this entity profile page.

**Popup modals for Level 2 users**
- [x] When I click 'Like,' I should see the popup modal called 'Like popup.'
- [x] I can click 'Get verified' to be taken to the verification page. After getting verified, I should be brought back to this entity profile page.
- [x] When I click 'Reply,' I should see the popup modal called 'Reply popup.'
- [x] I can click 'Get verified' to be taken to the verification page. After getting verified, I should be brought back to this entity profile page.
- [x] When I click 'Report,' I am taken to the reporting content page as normal.

**Popup modals for Level 2.5 users**
- [x] Having gotten verified despite Admin not yet approving my photo, when I click 'Like' or 'Reply,' I should see the popup modal called 'Hang on popup.'
- [x] Once Admin has approved my photo, 'Like' and 'Reply' buttons should work as normal.

- [x] I can click 'X' to close these popup modals.

**A new pop-up modal should appear when users click 'Helpful stuff' in the menu.**

<img width="358" alt="Screenshot 2019-12-22 at 07 42 29" src="https://user-images.githubusercontent.com/45825100/71318878-a2974500-248e-11ea-9923-206bd245f049.png">

Ensure consistency across both mobile and desktop.

**Comment by dupreesi** [comment]
@theharrisonmoore I've just filmed the current flow for level 1 users (logged in but not yet verified)
https://www.loom.com/share/e0ca3864cc9347f4b3645779eb23918e

so to be clear, you'd like for level 1 users to not be able to click Like, Reply or Report buttons at all but just a popup showing texy + get verified prompt?

**Comment by theharrisonmoore** [comment]
@dupreesi I'm still working on this issue and designing the wireframe for it. I'll be adding this later in the evening. Please could you work on bugs and outstanding issues before moving onto backlog stuff, thanks?

PS If you refer to the Access levels (https://docs.google.com/spreadsheets/d/1FYGTogNHkA85wl2gR2NrLbba2Nt5onO6DhI_OoIDSJw/edit#gid=1173862825), you will see that Level 1 users should not be able to Like, Reply or Report anything.

**Comment by dupreesi** [comment]
OK thanks @theharrisonmoore
