### ISSUE TITLE
Updates to level 2 > level 3 flow

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#918]
@thejoefriel We need to make the following changes to when a level 2 user (non-worker) tries to give a review and has to get verified.

Please refer to the page called 'Updated giving review journeys' in the wireframes.

- [x] Add new 'Verification required' page
- [x] Remove 'Important message for workers' page
- [x] After verification, ensure the giving review page follows
- [x] If user cancels at any point, return them to the entity profile page
- [x] If user cancels after uploading verification photo, keep them verified but return them to the entity profile page

Ensure consistency across both mobile and desktop

**Comment by RamyAlshurafa** [comment]
Hey @theharrisonmoore 
I can't find this `Updated giving review journeys` in the wireframes, are you using a new file?

**Comment by theharrisonmoore** [comment]
@ramy@yallacooperative.com <ramy@yallacooperative.com> Please don't work on
this issue. It is for the next Chunk 4. Please only work on bugs and issues
with priories attached. Thanks.

Best,
Harrison Moore
Sparky & founder
*earwig <http://earwigwork.com>*

ᐧ

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore really sorry but having issues with the files in figma rendering the text. Are you able to share the relevant wireframes as pictures here please so I can make sure no errors?

**Comment by theharrisonmoore** [comment]
@thejoefriel Sure, here you go:

<img width="1304" alt="Screenshot 2020-01-02 at 17 49 21" src="https://user-images.githubusercontent.com/45825100/71682649-45519c80-2d88-11ea-94ab-9c2270e7f105.png">

**Comment by RamyAlshurafa** [comment]
Hey @theharrisonmoore 
>Already verified? Log in

in this page the worker is already logged in, so shouldn't this be there?

![Verification required](https://user-images.githubusercontent.com/34629478/71777400-0ac64a80-2fa8-11ea-82fc-7254a17a3dc9.jpg)

**Comment by theharrisonmoore** [comment]
@ramy@yallacooperative.com <ramy@yallacooperative.com> @Joe Friel
<joe@yallacooperative.com> I'm sorry, I'm not sure what your question is
with this?

Best,
Harrison Moore
Sparky & founder
*earwig <http://earwigwork.com>*

ᐧ

**Comment by RamyAlshurafa** [comment]
Sorry I meant this:
![Verification required](https://user-images.githubusercontent.com/34629478/71782294-331e6b00-2fe1-11ea-8047-b24c270da8c9.jpg)

the user is already logged in, so I think there is no need for this message
