### ISSUE TITLE
On Lancer Square (worksite) profile, it says there are 4 reviews but only 2 are shown

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#938]
@thejoefriel On Lancer Square (worksite) profile, it says there are 4 reviews but only 2 are shown.

**Comment by RamyAlshurafa** [comment]
I'm sure that the 4 reviews are given, and only 2 of them contain voice or overall reviews, so this is not a bug. but I think it confuses,
so should we only show the number of reviews that have a voice or overall reviews?

**Comment by theharrisonmoore** [comment]
@RamyAlshurafa you're right. Yes, I think it would be good to only show a number of overall written or voice reviews.

**Comment by dupreesi** [comment]
@theharrisonmoore this def. makes sense for the profile section. 
should the number of reviews on the search page also be the count of overall written / voice reviews or rather stay as it is (total amount of all reviews)? 

![Bildschirmfoto 2019-12-23 um 11 26 23](https://user-images.githubusercontent.com/23721486/71352623-14e35480-2577-11ea-803e-83287b0718b9.png)
![Bildschirmfoto 2019-12-23 um 11 26 12](https://user-images.githubusercontent.com/23721486/71352626-17de4500-2577-11ea-9055-ba5faafbf0f7.png)

**Comment by dupreesi** [comment]
@theharrisonmoore I'll leave it like this for now as it covers the bug but if you feel that on the search page the reviews should also show only the ones incl. overall text / voice let's raise another issue.

**Comment by theharrisonmoore** [comment]
@Simon Dupree <simon@yallacooperative.com> I think you're right as you've
done it. Search pages should show the total number of reviews, the Overview
section shows the number of overall written/voice comments.

Best,
Harrison Moore
Sparky & founder
*earwig <http://earwigwork.com>*

ᐧ
