### ISSUE TITLE
Workers receive an email when others like or reply to them

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#946]
To keep the app "sticky" for workers and to help them know when others have given them points and replied to them, we need to send a notification email.

- [ ] As a worker, I receive an email when a user likes one of my comments (gives me a point)
**Subject line**: A worker just gave you a point for your helpful review on earwig!
**Main body**: Hey, a worker just gave you a point for your helpful review on earwig - keep up the good work and you can redeem your points for tools and training!
**Go to your review
Go to your points**

By the way, we know getting too many emails can be annoying. But please bear with us, we don't have an app yet so we can only use email to tell you about important developments. We're working as hard as we can to build an app so we don't have to send emails. We'll let you know (by email ;) when we've done it.

Thanks for your patience
Team earwig

- [ ] As a worker, I receive an email when a user replies to my comments
**Subject line**: A worker just replied to your review on earwig
**Main body**: Hey, a worker just replied to your review on earwig!
**Go to your review**

By the way, we know getting too many emails can be annoying. But please bear with us, we don't have an app yet so we can only use email to tell you about important developments. We're working as hard as we can to build an app so we don't have to send emails. We'll let you know (by email ;) when we've done it.

Thanks for your patience
Team earwig

- [ ] All emails to be sent from hello@earwig.work

**Comment by RamyAlshurafa** [comment]
Hey @theharrisonmoore 

>Go to your review

this wouldn't actually take the users to their review, it will take them to the profile where the review has been given in, I've discussed with @thejoefriel and he think this is ok for now and later we can build the functionality to take the user to the specific review position on the profile page, what do you think?

**Comment by thejoefriel** [comment]
Thanks @RamyAlshurafa . Yeah @theharrisonmoore this depends on how you want to approach. We feel the more agile approach at this stage would be that it takes them to the profile where the review has been given. This will then let you go back to users and test this flow to see if getting email notifications is something they like etc. This would also require less dev time so be more cost-efficient. 

However, if you want us to take them to the specific review we can certainly do this, it'll just take a bit more dev time. 

Let me know what you think. Happy to jump on the phone to discuss.

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> @ramy@yallacooperative.com
<ramy@yallacooperative.com> Hi, can you show me where you see 'Go to your
review'? I'm not aware of this anywhere in the app.

Best,
Harrison Moore
Sparky & founder
*earwig <http://earwigwork.com>*

ᐧ

**Comment by RamyAlshurafa** [comment]
in this issue, in the first email body

**Comment by theharrisonmoore** [comment]
Ah yes, I see now. Sorry about that.

Yes, as you say, let's keep it simple. Just take them to the profile.

Best,
Harrison Moore
Sparky & founder
*earwig <http://earwigwork.com>*

ᐧ

**Comment by RamyAlshurafa** [comment]
cool, Thanks
