### ISSUE TITLE
Investigate GitHub error report

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#960]
@thejoefriel Here's the email I got:
<img width="735" alt="Screenshot 2019-12-30 at 10 59 55" src="https://user-images.githubusercontent.com/45825100/71579276-ca705380-2af3-11ea-8c11-40429db4aa5f.png">

**Comment by thejoefriel** [comment]
Hey I've been looking into this and I think an old version of handlebars is a required dependency for Istanbul. We don't use Istanbul so I think we can simply uninstall Istanbul - @RamyAlshurafa what do you think? Are you aware of Istanbul being needed at all?

**Comment by RamyAlshurafa** [comment]
yeah, I think yeah you can remove it
