### ISSUE TITLE
Comments for Parking Question

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#973]
Hi @theharrisonmoore 

We had a quick question! For the question on worksite "Was there car parking within 10 minutes walk of this site?" there is a comment box as you'd expect for them to add further notes. 

However, when you select yes, and it then asks how much it was, there's another comment box there currently. Since both answers are then rendered as part of the same question on the profile, we've realised that any comments in the second comment box aren't rendered in the profile. 

Here's the flow showing what I mean: https://www.loom.com/share/6fb8039006a8472d8738654b96928eb5

We can spend some time looking into collating these comments (although this would take quite a bit of work). However, I first wanted to check whether we needed the second comment box? It feels to me that the price is a part of the same question (hence they're rendered together on the profile) so any comment a user would write would be in the first comment box. 

What do you think? If you agree, we can simply remove the second comment box.

**Comment by theharrisonmoore** [comment]
@thejoefriel Yes I agree, please remove the second comment box, leaving only the first.
