### ISSUE TITLE
Bugs in emails

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#984]
### Welcome email #1
As a new user, I receive a welcome email. In the email, there's a link called 'Read reviews and ratings.' This currently takes me to the agency search page when it should always take me to the Welcome page.

Also, in this welcome email, the following text should be removed:
![IMG_0454](https://user-images.githubusercontent.com/45825100/72155083-2d8e9f80-33aa-11ea-9217-5cdc99ed6568.jpg)

### Welcome email #2
As a user who has just uploaded a photo for verification, I receive a welcome email. In this email, the following text needs to be removed:
![IMG_0456](https://user-images.githubusercontent.com/45825100/72155211-865e3800-33aa-11ea-9c83-3319c7f398b6.jpg)

Also, in this welcome email, the following link is broken. It should take users to the Welcome page:
![IMG_0455](https://user-images.githubusercontent.com/45825100/72155284-af7ec880-33aa-11ea-88c5-04107673ac34.jpg)

### Email when worker likes or replies
When we click these links, we have to log back into earwig despite being logged in already.
![IMG_0470](https://user-images.githubusercontent.com/45825100/72163978-c4645780-33bc-11ea-829a-ba4bd20b1aa8.jpg)

**Comment by dupreesi** [comment]
outsourcing the logging issue to a new one!
